= Setup

:workingdir: lis-public-testcases

[IMPORTANT]
====
If you have not set up your computing environment to compile and run the LISF code, review the {url-lisf-docs}[official documentation,window=_blank].

Users on NASA's NCCS Discover HPC system should review _Quick Start Guide for NCCS Discover Users_ in link:{url-lisf-docs}[our docs].
====

== Create a working directory

To begin, create and step into a working directory that you will use throughout the testcases. This directory will be referred to as `$WORKING_DIR` from this point forward. In the following example, we create a working directory called `{workingdir}`:

[#create-workingdir]
[source,shell,subs="attributes"]
----
% mkdir {workingdir}
% cd {workingdir}
----

== Clone the LISF Repository

From inside your `$WORKING_DIR`, clone the public support branch of the link:{url-lisf-github}[LISF repository]:

[#clone-lis]
[source,shell,subs="attributes"]
----
% git clone -b {compatible-lisf-branch} {ssh-lisf-github}
% cd LISF
----

IMPORTANT: The `{compatible-lisf-branch}` branch is known to be compatible with the testcase files. The `master` branch may contain changes to the LISF source code that break compatibility with the testcase files. We therefore recommend using the support branch while working through these testcases.

== Configure and Compile the LISF Components

For information about configuration settings and detailed compilation instructions, see the {url-lisf-docs}[LISF Users' Guides,window=_blank]. In general, the compilation process for each component is as follows:

NOTE: As you run these testcases, you will have the opportunity to compare your output to TARGET_OUTPUT files or "solutions".  The TARGET_OUTPUT files were created by running ldt, lis, and lvt compiled with *default* compile configuration settings.  For this walkthrough, it is recommended that you also use default compiler configuration settings.   

[#compile-example]
[source,shell,subs="attributes"]
----
% cd ldt
% ./configure
> # Select compile configuration settings (Default settings recommended.)
% ./compile
> # Compilation output...
% mv LDT ../../            # move executable up into $WORKING_DIR
% cd ..                    # change directories back into LISF
----

Repeat the above process in the `lis/` and `lvt/` directories to generate the _LIS_ and _LVT_ executables.

Change directories back into your `$WORKING_DIR` which should now contain three executable files: `LDT`, `LIS`, `LVT`.

If you ever wish to generate new executable files, `cd` into `/LISF/l??/make` and run `gmake realclean`.  This will clear all dependency files and allow you to cleanly define new compile configuration settings and recompile. 
