= Step 2: LSM "Open-loop" (OL) Experiment (LIS)

:step-label: Step 2
:download-filename: testcase2_lis_ol_2023.tar.gz
:input-filesize-compressed: 65MB
:input-filesize-unpacked: 343MB

== Overview

In this step you will learn how to run LIS with the Noah-3.6 LSM for an "open-loop" case. This testcase uses the files generated by LDT in Step 1.

=== Steps to Running LIS

. Download input data (e.g., meteorolgical forcing, observations)
. Modify the `lis.config` file to select runtime options
. Run the LIS executable
. Examine output

include::download_input_files.adoc[]

The following files and directories were added to your common working directory, `$WORKING_DIR`:

[cols="2*",frame=topbot,stripes=odd]
[%autowidth]
|===
|`INPUT/wget_gesdisc_nldas2.sh`     |A script to download NLDAS2 forcing data
|`INPUT/NOAH36_OUTPUT_LIST.TBL`     |Model output specification
|`INPUT/forcing_variables.txt`      |Forcing variable specification
|`INPUT/LS_PARAMETERS`              |Model parameter specification
|`lis.config_noah36_ol`             |The runtime configuration file that will be read by LIS
|`target_log/lislog_ol.0000`        |The "target" log file that should be produced by LIS in this step
|`target_OL_OUTPUT/`                |A directory containing containing the "target" open-loop (OL) output files that should be generated by LIS in this step
|`target_ol.xdf`                    |GrADS descriptor file for visualizing outputs
|===

=== Download the Meteorological Forcing Dataset

This testcase is set up to use the link:https://ldas.gsfc.nasa.gov/nldas/v2/forcing[_North American Data Assimilation System, version 2 (NLDAS-2)_] meteorological forcing dataset available from link:https://disc.gsfc.nasa.gov/datasets/NLDAS_FORA0125_H_002/summary[NASA GES DISC]. A script has been provided in the input files that uses `wget` to download these data.

[NOTE]
====
Users on NASA's NCCS Discover HPC system do not need to download the data as described below. Instead, change directories into `INPUT/` and create a symbolic link to a local copy:

[source,shell]
----
% ln -s /discover/nobackup/projects/lis/MET_FORCING/NLDAS2.FORCING NLDAS2.FORCING
----

Jump to the <<The LIS Configuration File,next step>>.
====

[IMPORTANT]
====
Before running the download script:

. If needed, install `wget`
. Create a link:https://urs.earthdata.nasa.gov/users/new[NASA Earthdata] account if you do not already have one
. Follow steps 1-3 in link:https://disc.gsfc.nasa.gov/data-access#mac_linux_wget[these instructions] to save your NASA Earthdata login credentials locally
====

When you are ready to run the script, change directories into `INPUT/` and run the following command:

[source,shell]
----
% sh wget_gesdisc_nldas2.sh
----

The script will download NLDAS-2 forcing data for the entire year of 2017 into a directory named `NLDAS2.FORCING/`. If the script completes without any errors, change up one directory back to your `$WORKING_DIR`. If any errors are thrown, attempt to resolve them.

== The LIS Configuration File

The main LIS configuration file (`lis.config_noah36_ol`) is where runtime options and filepaths used during the run are defined. These include:

* The LSM of interest (e.g., Noah.3.6)
* The name of the NetCDF-parameter file created by LDT in the previous step (e.g., `lis_input.nldas.noah36.d01.nc`)
* The name of the LIS diagnostic file (e.g., `lislog`)
* The date and time inputs, model options, parallel domain entries, etc.
* Meteorological forcing dataset(s) selected; also some downscaling features
* Data assimilation entries, and other features, such as irrigation or runoff routing

Open the LIS configuration file in a text editor to view these settings and more.

You may notice that the grid domain is not contained in this file. The grid domain that was defined in the `ldt.config` file is now contained in the NetCDF-formatted parameter file (`lis_input.nldas.noah36.d01.nc`) and this information will be read by LIS at runtime.

== Run LIS - The "Open-Loop" (OL) Step

You are now ready to run LIS.

In your `$WORKING_DIR`, execute the following command:

[source,shell]
----
% ./LIS -f lis.config_noah36_ol
----

[NOTE]
====
LIS can also be run in parallel. The examples in this walkthrough, however, demonstrate how to run LIS on a single processor. See Chapter 6 in link:{url-lisf-docs}[the LIS Users' Guide] for instructions for running LIS in parallel.
====

With a single processor the run should take approximately 20 minutes to complete. If the run fails, diagnose the issue by reviewing any errors that have printed to the terminal and by viewing the contents of `lislog` files (located in the `log` directory as defined by line 42 of `lis.config_noah36_ol`). If no errors appear and the run appears to have completed successfully, examine the end of any `lislog` files present to check for a confirmation message:

[source,shell]
----
% tail lislog.0000
 [INFO] LIS cycle completed
[INFO] LIS cycle time: 01/01/2018 00:00:00
 [INFO] getting file2a.. 
 ./INPUT/NLDAS2.FORCING/2018/001/NLDAS_FORA0125_H.A20180101.0100.002.grb
 [ERR] Could not find file: 
 ./INPUT/NLDAS2.FORCING/2018/001/NLDAS_FORA0125_H.A20180101.0100.002.grb
 [INFO] Noah-3.6 archive restart written: 
 ./OL_OUTPUT/SURFACEMODEL/201801/LIS_RST_NOAH36_201801010000.d01.nc             
                      
  LIS Run completed.
----

Use `ls` to view the files and directories created by LIS.

== LIS Output Files

The output files created by LIS were placed into a new directory called `OL_OUTPUT`. Within this directory is another directory called `SURFACEMODEL` which contains subdirectories following the naming convention `YYYYMM`:

* YYYY icon:arrow-right[] 4-digit year
* MM icon:arrow-right[] 2-digit month

Within each of those subdirectories are NetCDF-formatted LIS output files that contain the Noah-3.6 output variables defined in `NOAH36_OUTPUT_LIST.TBL` (e.g., soil moisture, runoff, evapotranspiration). Use any visualization package you are comfortable with to view the files (e.g., Matlab, GrADS, `ncview`). For GrADS users, descriptor files are provided with the input data.

// TODO: ADD EXAMPLE HERE

== Wrap-up

You have now generated your LIS Noah-3.6 model run for the open-loop case. Use `diff` and `nccmp` to compare the output files you generated with the "target" versions found in `target_OL_OUTPUT/`. As in Step 1, the files you generated in this step will be used in later steps.
