= Step 3: Ensemble Restart File Generation (LDT)

:step-label: Step 3
:download-filename: testcase3_ldt_ensrst_2023.tar.gz
:input-filesize-compressed: 97KB
:input-filesize-unpacked: 100KB

:ldt-run-dir: DA_ensrst
:ldt-config-filename: ldt.config

== Overview

In Step 1, you used LDT to perform parameter processing for the Noah-3.6 land surface model (LSM) to generate a Noah-3.6 parameter input file to be used by LIS (and LVT). In addition to parameter processing, LDT can be used to _upscale_ and _downscale_ ensembles.

[NOTE]
====

*Upscale:* generate a multi-member ensemble restart file from a single-member restart file

*Downscale:* generate a single-member ensemble restart file from a multi-member restart file

====

In this step you will learn how to use LDT to expand a single-member *restart* file generated by the LIS open-loop (OL) case in Step 2 into a restart file that contains an ensemble of size _N_ (user specified). The ensemble restart file generated in this step will be used in Step 6 to *initialize* the LIS data assimilation (DA) run.

[NOTE]
====

[quote, http://www.cesm.ucar.edu/models/ccsm2.0/csim/UsersGuide/ice_usrdoc/node21.html]

*Restart files* contain all of the initial condition information necessary to restart from a previous simulation.

====

include::download_input_files.adoc[]

The following files and directories were added to your common working directory, `$WORKING_DIR`:

[cols="2*",frame=topbot,stripes=odd]
[%autowidth]
|===
|`DA_ensrst/`                                     |A directory containing the files below
|`ldt.config`                                     |The LDT config file for this step
|`target_ldtlog.0000`                             |The target LDT log file
|`target_LIS_EnRST_NOAH36_201801010000.d01.nc`    |The target LDT-generated ensemble restart file ("EnRST") to start the Noah LSM DA run in Step 6
|===

== The LDT Configuration File

Review the contents of `DA_ensrst/ldt.config` to view the configuration settings used for this step:

[#cat-ldtconfig]
[source,shell]
----
LDT running mode:                               "Ensemble restart processing"
Processed LSM parameter filename:               ./lis_input.nldas.noah36.d01.nc
...
LIS restart source:                             "LSM"
Ensemble restart generation mode:               "upscale" <1>
Input restart filename:                         ../OL_OUTPUT/SURFACEMODEL/201801/LIS_RST_NOAH36_201801010000.d01.nc
Number of ensembles per tile (input restart):   1 <2>
Number of ensembles per tile (output restart):  12 <3>
----
<1> This entry tells LDT how to process the _ensemble_ file
<2> Size of input ensemble restart file, in this case a single instance of model states
<3> Size of upscaled multi-member ensemble restart file, in this case 12 members

In this walkthrough we are using the Noah.3.6 LSM, but these settings can be used to upscale/downscale routing models as well. For example:

[source,shell]
----
LIS restart source:                             "Routing"
Ensemble restart generation mode:               "upscale"
Input restart filename:                         ./LIS_RST_HYMAP_router_201801010000.d01.bin
Output restart filename:                        ./ensrst.bin
Number of ensembles per tile (input restart):   1
Number of ensembles per tile (output restart):  12
----

== Run LDT -  Generate Ensemble Restart File

include::running_ldt.adoc[]

== LDT Output Files

During this run, LDT produced one output file named `LIS_EnRST_NOAH36_201801010000.d01.nc` and placed it into the `$WORKING_DIR/DA_ensrst` directory.

Use `ncview`, Panoply, Matlab or any other viewing package that supports NetCDF files. Compare what you see with the _target_ version of this output file, also located in `$WORKING_DIR/DA_ensrst`. Additionally, you can use `nccmp` to directly compare the contents of the file created by your LDT run and the target. If there are differences between your file and the target file, you can use `ncdiff` to create a new NetCDF file to visualize the differences. 

// TODO: ADD EXAMPLES HERE
