#==============================================================================
#
# Makefile for Units_Conversion test code
#
# $Id: Makefile 1958 2008-03-18 16:35:36Z paul.vandelst@noaa.gov $
#==============================================================================

# Define the executable file
EXE_FILE = Units_Conversion_Test

# include the common make components
include ../make.common

# The run target
run: all
	$(EXE_FILE)

# include the dependency list
include make.dependencies
