#if 0

          !!! WARNING !!!
This is a generated file.  Do not manually edit.
To enable/disable optional components, please create a user.cfg file.
See the LIS Users' Guide for more informaion.

#endif
#define RM_RETROSPECTIVE
#define RM_AGRMETMODE
#define RM_WRF_COUPLING
#undef RM_GCE_COUPLING
#define RM_PARAM_ESTIMATION
#define RM_RTM_FORWARD
#define RM_ENSEMBLE_SMOOTHER
#define RM_FORECAST
#define MF_MET_TEMPLATE
#define MF_LDT_GENERATED
#define MF_CLIMATOLOGY
#define MF_GENENSFCST
#define MF_PPTENSFCST
#define MF_GDAS
#define MF_GDAS_T1534
#define MF_GEOS5_FORECAST
#define MF_GEFS_FORECAST
#define MF_ECMWF
#define MF_GSWP1
#define MF_GSWP2
#define MF_AGRMET
#define MF_PRINCETON
#define MF_NLDAS2
#define MF_GLDAS
#define MF_GFS
#define MF_MERRA2
#define MF_GEOS_IT
#define MF_ERA5
#define MF_CMAP
#define MF_CHIRPS2
#define MF_TRMM_3B42RT
#define MF_TRMM_3B42RTV7
#define MF_TRMM_3B42V6
#define MF_TRMM_3B42V7
#define MF_CPC_CMORPH
#define MF_GPM_IMERG
#define MF_CPC_STAGEII
#define MF_CPC_STAGEIV
#define MF_NARR
#define MF_RFE2_DAILY
#define MF_SCAN
#define MF_AGRMET_RADIATION_POLAR_STEREOGRAPHIC
#define MF_PLUMBER2
#define MF_BONDVILLE
#undef MF_TRIGRS_TEST
#define MF_SNOTEL
#define MF_RFE2_GDAS_BIAS_CORRECTED
#undef MF_VIC_PROCESSED_FORCING
#define MF_PALS_STATION_FORCING
#define MF_PET_USGS
#define MF_NAM242
#define MF_WRFOUT
#define MF_COAMPSOUT
#define MF_WRFOUTV2
#define MF_WRF_AK
#define MF_AWAP
#define MF_AWRAL
#define MF_HIMAT_GMU
#define MF_LOOBOS
#define MF_MRMS
#define MF_GDDP
#define MF_GALWEM_FORECAST
#define MF_GALWEM_GE_FORECAST
#define MF_MOGREPS_G_FORECAST
#undef PARAM_MODIS_REAL_TIME
#define PARAM_ALMIPII_LAI
#define PARAM_NESDIS_WEEKLY
#define PARAM_SPORT
#define PARAM_VIIRS
#define PARAM_ALMIPII_GFRAC
#define PARAM_ALMIPII_ROUGHNESS
#define PARAM_ALMIPII_ALBEDO
#define PARAM_ALMIPII_EMISSIVITY
#undef RTMS_CRTM
#define RTMS_CRTM2
#define RTMS_CRTM2EM
#define RTMS_CMEM
#define RTMS_TAU_OMEGA
#define APP_GLS
#define APP_TRIGRS
#define ROUTE_NLDAS_ROUTER
#undef ROUTE_HYMAP_ROUTER
#define ROUTE_HYMAP2_ROUTER
#define ROUTE_RAPID_ROUTER
#define IRR_SPRINKLER
#define IRR_FLOOD
#define IRR_DRIP
#define DA_DIRECT_INSERTION
#define DA_ENKF
#define DA_ENSRF
#define DA_EKF
#define DA_ENKS
#define DA_PF
#define DA_OBS_SYNTHETICSM
#define DA_OBS_SYNTHETICWL
#define DA_OBS_HYDROWEBWL
#define DA_OBS_SYNTHETICSND
#define DA_OBS_SYNTHETICSNOWTB
#define DA_OBS_SNODEP
#define DA_OBS_USAFSI
#define DA_OBS_SNIP
#define DA_OBS_PMW_SNOW
#define DA_OBS_ANSA_SCF
#define DA_OBS_ESACCI_SM
#define DA_OBS_THYSM
#define DA_OBS_LPRM_AMSRESM
#define DA_OBS_SMMR_SNWD
#define DA_OBS_SSMI_SNWD
#define DA_OBS_ANSA_SNWD
#define DA_OBS_GCOMW_AMSR2L3SND
#define DA_OBS_SNODAS
#define DA_OBS_WUSUCLA
#define DA_OBS_SMOPS_ASCATSM
#undef DA_OBS_SMOPS_SMOSSM
#undef DA_OBS_SMOPS_AMSR2SM
#undef DA_OBS_SMOPS_SMAPSM
#define DA_OBS_SMOS_NESDIS
#define DA_OBS_NASA_SMAPSM
#define DA_OBS_SMOS_NRT_NN
#define DA_OBS_SMAP_E_OPL_SM
#define DA_OBS_WSF_SM
#define DA_OBS_NASA_SMAPVOD
#define DA_OBS_ASO_SWE
#define DA_OBS_MCD15A2H_LAI
#define DA_OBS_GLASS_LAI
#define DA_OBS_VIIRS_GVF
#define DA_OBS_CDFS_GVF
#define DA_OBS_GLASS_Albedo
#define DA_OBS_MODISSPORT_LAI
#define DA_OBS_NRT_SMAPSM
#define DA_OBS_PILDAS
#define DA_OBS_GRACE
#define DA_CDF_TRANSFER_NASA_SMAPSM
#define BE_bias_estimation
#define PERT_perturbations
#define OPTUE_ALG_ES
#define OPTUE_ALG_LM
#define OPTUE_ALG_GA
#define OPTUE_ALG_SCEUA
#define OPTUE_ALG_MCSIM
#define OPTUE_ALG_RWMCMC
#define OPTUE_ALG_DEMC
#define OPTUE_ALG_DEMCZ
#define PE_OBS_TEMPLATE
#define PE_OBS_PESYNSM1
#define PE_OBS_ISCCP_TSKIN
#define PE_OBS_WGPBMRSM
#define PE_OBS_CNRS
#define PE_OBS_AMSRE_SR
#define PE_OBS_LPRM_AMSRESM
#define PE_OBS_EMPTYOBS
#define PE_OBS_ARM
#define PE_OBS_MACON_LS_DATA
#define PE_OBS_GLOBAL_LS_DATA
#define PE_OBS_AMERIFLUX
#define PE_OBS_FLUXNET
#define PE_OBS_USDA_ARSSM
#define PE_OBS_ARSSM
#define PE_OBS_ISMNSM
#define PE_OBS_SMAPSM
#define PE_OBS_UASNOW
#define PE_OBJFUNC_LS
#define PE_OBJFUNC_LM
#define PE_OBJFUNC_LL
#define PE_OBJFUNC_P
#define SM_LSM_TEMPLATE
#define SM_NOAH_2_7_1
#define SM_NOAH_3_2
#define SM_NOAH_3_3
#define SM_NOAH_3_6
#define SM_NOAH_3_9
#define SM_NOAHMP_3_6
#define SM_NOAHMP_4_0_1
#define SM_RUC_3_7
#undef SM_CLM_2
#undef SM_VIC_4_1_1
#undef SM_VIC_4_1_2
#define SM_AWRAL_6_0_0
#define SM_MOSAIC
#define SM_HYSSIB
#undef SM_JULES_4_3
#undef SM_JULES_5_0
#undef SM_JULES_5_1
#undef SM_JULES_5_2
#undef SM_JULES_5_3
#undef SM_JULES_5_4
#undef SM_JULES_5_X
#define SM_CABLE
#undef SM_FASST
#define SM_CLSM_F2_5
#define SM_GEOWRSI_2
#undef SM_RDHM_3_5_6
#undef SM_SUMMA_1_0
#undef SM_Crocus_8_1
#undef SM_SNOWMODEL
#undef SM_FLAKE_1_0
#define SM_NOAHMP_GLACIER_3_9_1_1
#define SM_GLACIER_TEMPLATE
#define SM_TEMPLATE_OPEN_WATER
#define FA_ESPBOOT
#define FA_ESPCONV
