#define USE_NETCDF4 
#define USE_GRIBAPI 
#define USE_ECCODES 
#define AFWA_GRIB_CONFIGS 
#define USE_HDF4 
#define USE_HDFEOS2 
#define USE_HDF5 
#undef USE_MINPACK 
#undef RTMS 
#define PETSc 
#undef INC_WATER_PTS
#undef COUPLED
#undef USAF_LIS75_SMDA 
