#define USE_NETCDF4 
#define USE_GRIBAPI 
#define USE_ECCODES 
#undef AFWA_GRIB_CONFIGS 
#define USE_HDF4 
#define USE_HDF5 
#undef USE_MINPACK 
#undef RTMS 
#undef LAPACK 
#undef MKL_LAPACK 
#undef INC_WATER_PTS
#undef COUPLED
#undef SFX_MNH
#define MNH_MPI_DOUBLE_PRECISION
