
[[sec-metricslisttable]]
== Configuration of metrics

This section defines the specification of various metrics in LVT. This file is specified in a space delimited column format. Each row consists of the following entries:

`Name`: Name of the metric

`Use option`: determines whether to use this metric. When enabled, the metric will be computed through the duration of the evaluation and a final file will be written out. Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not use the metric
| 1     | use the metric
|===

`Time option`: specifies whether to compute the metric in time, at the specified stats output intervals. Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not compute the metric
| 1     | compute the metric
|===

`Temporal output`: determines whether to write (gridded) metric files at the specified stats output intervals. The "`Time option`" must also be enabled when this option is enabled. Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not write gridded files
| 1     | write gridded time files
|===

`Extract time series`: determines whether to extract (ASCII) time series files for the metric, at each sub-domain specified in the time series location file. Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not write ASCII files
| 1     | write ASCII time files
|===

`Threshold`: specifies the threshold values to be used in computing the metric. Note that this is used only for the categorical metrics. Two values must be specified. The first value is the minimum threshold and the second values is the maximum threshold.

`Compute average seasonal cycle`: determines whether to generate the average seasonal cycle of the metric (for each domain specified in the time series location file). Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not generate
| 1     | generate seasonal cycle
|===

`Compute average diurnal cycle`: determines whether to generate the average diurnal cycle of the metric (for each domain specified in the time series location file). Acceptable values are:

[cols="<,<",]
|===
| Value | Description

| 0     | do not generate
| 1     | generate diurnal cycle
|===

....
#name                                 Use  Time  WriteTS  ExtractTS  Threshold(min/max)  ASC  ADC  short_name
Mean:                                  1    1       1         1       -9999.0  -9999.0    1    0  #MEAN
Anomaly:                               0    0       0         0       -9999.0  -9999.0    0    0  #Anomaly
Min:                                   0    0       0         0       -9999.0  -9999.0    0    0  #MIN
Max:                                   0    0       0         0       -9999.0  -9999.0    0    0  #MAX
MinTime:                               0    0       0         0       -9999.0  -9999.0    0    0  #MINTIME
MaxTime:                               0    0       0         0       -9999.0  -9999.0    0    0  #MAXTIME
Sum:                                   0    0       0         0       -9999.0  -9999.0    0    0  #SUM
Standard deviation:                    0    0       0         0       -9999.0  -9999.0    0    0  #STDEV
Variance:                              0    0       0         0       -9999.0  -9999.0    0    0  #VARIANCE
Bias:                                  0    0       0         0       -9999.0  -9999.0    0    0  #BIAS
RMSE:                                  0    0       0         0       -9999.0  -9999.0    0    0  #RMSE
ubRMSE:                                0    0       0         0       -9999.0  -9999.0    0    0  #ubRMSE
Anomaly RMSE:                          0    0       0         0       -9999.0  -9999.0    0    0  #ARMSE
Mean absolute error:                   0    0       0         0       -9999.0  -9999.0    0    0  #MAE
Anomaly correlation:                   0    0       0         0       -9999.0  -9999.0    0    0  #ACORR
Raw correlation:                       0    0       0         0       -9999.0  -9999.0    0    0  #RCORR
Rank correlation:                      0    0       0         0       -9999.0  -9999.0    0    0  #RNKCORR
Anomaly rank correlation:              0    0       0         0       -9999.0  -9999.0    0    0  #ARNKCORR
Probability of detection (PODy):       0    0       0         0           0.1      0.3    0    0  #PODY
Probability of detection (PODn):       0    0       0         0           0.1      0.3    0    0  #PODN
False alarm ratio (FAR):               0    0       0         0           0.1      0.3    0    0  #FAR
Detection failure ratio (DFR):         0    0       0         0           0.1      0.3    0    0  #DFR
Probability of false detection (POFD): 0    0       0         0           0.1      0.3    0    0  #POFD
Critical success index (CSI):          0    0       0         0           0.1      0.3    0    0  #CSI
Accuracy measure (ACC):                0    0       0         0           0.1      0.3    0    0  #ACC
Frequency bias (FBIAS):                0    0       0         0           0.1      0.3    0    0  #FBIAS
Equitable threat score (ETS):          0    0       0         0           0.1      0.3    0    0  #ETS
Event frequency (EF):                  0    0       0         0           0.1      0.3    0    0  #EF
Forecast frequency (FF):               0    0       0         0           0.1      0.3    0    0  #FF
Heidke skill score (HSS):              0    0       0         0           0.1      0.3    0    0  #HSS
Peirce skill score (PSS):              0    0       0         0           0.1      0.3    0    0  #PSS
Clayton skill score (CSS):             0    0       0         0           0.1      0.3    0    0  #CSS
Area metric:                           0    0       0         0       -9999.0  -9999.0    0    0  #AREA
Nash sutcliffe efficiency:             0    0       0         0       -9999.0  -9999.0    0    0  #NSE
Metric entropy:                        0    0       0         0       -9999.0  -9999.0    0    0  #Mentropy
Information gain:                      0    0       0         0       -9999.0  -9999.0    0    0  #Igain
Fluctuation complexity:                0    0       0         0       -9999.0  -9999.0    0    0  #Fcomplexity
Effective complexity:                  0    0       0         0       -9999.0  -9999.0    0    0  #Ecomplexity
Wavelet stat:                          0    0       0         0       -9999.0  -9999.0    0    0  #Waveletstat
Hausdorff norm:                        0    0       0         0       -9999.0  -9999.0    0    0  #Hnorm
Standard precipitation index:          0    0       0         0       -9999.0  -9999.0    0    0  #SPI
Standard runoff index:                 0    0       0         0       -9999.0  -9999.0    0    0  #SRI
Standard dS index:                     0    0       0         0       -9999.0  -9999.0    0    0  #SdSI
Standardized soil water index:         0    0       0         0       -9999.0  -9999.0    0    0  #SSWI
Standardized ground water index:       0    0       0         0       -9999.0  -9999.0    0    0  #SGWI
Percentile:                            0    0       0         0       -9999.0  -9999.0    0    0  #Percentile
River flow variate:                    0    0       0         0       -9999.0  -9999.0    0    0  #RFV
Tendency:                              0    0       0         0       -9999.0  -9999.0    0    0  #TENDENCY
Tendency correlation:                  0    0       0         0       -9999.0  -9999.0    0    0  #TENDENCYCORR
Z score:                               0    0       0         0       -9999.0  -9999.0    0    0  #ZSCORE
Trend:                                 0    0       0         0       -9999.0  -9999.0    0    0  #TREND
Triple collocation:                    0    0       0         0       -9999.0  -9999.0    0    0  #TC
Reliability:                           0    0       0         0       -9999.0  -9999.0    0    0  #REL
Resilience:                            0    0       0         0       -9999.0  -9999.0    0    0  #RES
Vulnerability:                         0    0       0         0       -9999.0  -9999.0    0    0  #VUL
Information entropy:                   0    0       0         0       -9999.0  -9999.0    0    0  #IE
Conditional entropy:                   0    0       0         0       -9999.0  -9999.0    0    0  #CE
Joint entropy:                         0    0       0         0       -9999.0  -9999.0    0    0  #JE
Relative entropy:                      0    0       0         0       -9999.0  -9999.0    0    0  #RE
Mutual information:                    0    0       0         0       -9999.0  -9999.0    0    0  #MI
....

