
== Background
anchor:sec_backgrd[Background]

This section provides some general information about the LIS project.


=== LIS

Land Information System (LIS) is a flexible land surface modeling and data assimilation framework developed with the goal to integrate satellite- and ground-based observational data products and advanced land surface modeling techniques to produce optimal fields of land surface states and fluxes. The LIS infrastructure provides the modeling tools to integrate these observations with model forecasts to generate improved estimates of land surface conditions such as soil moisture, evaporation, snow pack, and runoff, at 1km and finer spatial resolutions and at one-hour and finer temporal resolutions. The fine scale spatial modeling capability of LIS allows it take advantage of the EOS-era observations, such as MODIS leaf area index, snow cover, and surface temperature, at their full native resolution. LIS features a high performance and flexible design, provides infrastructure for data integration and assimilation, and operates on an ensemble of land surface models (LSM) for extension over user-specified regional or global domains. LIS is designed using advanced software engineering principles to enable reuse and community sharing of modeling tools, data resources, and assimilation algorithms. The system is designed as an object-oriented framework, with abstractions defined for customization and extension to different applications. These extensible interfaces allow the incorporation of new domains, LSMs, land surface parameters, meteorological inputs, data assimilation and optimization algorithms.  The extensible nature of these interfaces and the component style specification of the system allow rapid prototyping and development of new applications. These features enable LIS to serve both as a Problem Solving Environment (PSE) for hydrologic research to enable accurate global water and energy cycle predictions, and as a Decision Support System (DSS) to generate useful information for application areas including disaster management, water resources management, agricultural management, numerical weather prediction, air quality and military mobility assessment.

LIS currently includes a comprehensive suite of subsystems to support uncoupled and coupled land data assimilation. A schematic of the LIS framework with the associated subsystems are shown in the Figure below.  The LIS-LSM subsystem, which is the core of LIS, supports high performance, interoperable and portable land surface modeling with a suite of community land surface models and input data. Further, the LIS-LSM subsystem is designed to encapsulate the land surface component of an Earth System model. The LIS-WRF subsystem supports coupled land-atmosphere modeling through both one-way and two-way coupling to the WRF atmospheric model, leading to a hydrometeorological modeling capability that can be used to evaluate the impact of land surface processes on hydrologic prediction. The Data Assimilation (LIS-DA) subsystem supports multiple data assimilation algorithms that are focused on generating improved estimates of hydrologic model states.  Finally, the Optimization (LIS-OPT) subsystem supports a suite of advanced optimization and uncertainty modeling tools in LIS.

include::components.adoc[]

