
=== LIS core

The central part of LIS software system is the LIS core that controls program execution. The LIS core is a model control and input/output system (consisting of a number of subroutines, modules written in Fortran 90 source code) that drives multiple offline one-dimensional LSMs.  The one-dimensional LSMs such as CLM and Noah, apply the governing equations of the physical processes of the soil-vegetation-snowpack medium. These land surface models aim to characterize the transfer of mass, energy, and momentum between a vegetated surface and the atmosphere. When there are multiple vegetation types inside a grid box, the grid box is further divided into "`tiles`", with each tile representing a specific vegetation type within the grid box, in order to simulate sub-grid scale variability.

The execution of the LIS core starts with reading in the user specifications, including the modeling domain, spatial resolution, duration of the run, etc.  Section <<sec_run>> describes the exhaustive list of parameters specified by the user. This is followed by the reading and computing of model parameters.  The time loop begins and forcing data is read, time/space interpolation is computed and modified as necessary. Forcing data is used to specify the boundary conditions to the land surface model. The LIS core applies time/space interpolation to convert the forcing data to the appropriate resolution required by the model. The selected model is run for a vector of "`tiles`" and output and restart files are written at the specified output interval.

Some of the salient features provided by the LIS core include:

* Vegetation type-based "`tile`" or "`patch`" approach to simulate
  sub-grid scale variability.
* Makes use of various satellite and ground-based observational
  systems.
* Derives model parameters from existing topography, vegetation,
  and soil coverages.
* Extensible interfaces to facilitate incorporation of new
  land surface models, forcing schemes.
* Uses a modular, object oriented style design that allows
  "`plug and play`" of different features by allowing user to
  select only the components of interest while building the executable.
* Ability to perform regional modeling (only on the domain of
  interest).
* Provides a number of scalable parallel processing modes of
  operation.

Please refer to the software design document for a detailed description of the design of LIS core. The LIS reference manual provides a description of the extensible interfaces in LIS. The "`plug and play`" feature of different components is described in this document.

//=== GrADS-DODS Server
//
//A GrADS-DODS Server (GDS) is a data server built upon the Grid
//Analysis and Display System (GrADS) and the Distributed Oceanographic
//Data System (DODS).
//
//GrADS is an earth science data manipulation and visualization tool
//under development at the Center for Ocean-Land-Atmosphere Studies
//(COLA) (http://http://grads.iges.org/cola.html).  See
//http://grads.iges.org/grads/grads.html for more detailed information
//about GrADS.
//
//DODS, also called the Open source Project for a Network Data Access
//Protocol (OPeNDAP), is a protocol for serving data-sets stored in
//various formats over a network.  See
//http://www.unidata.ucar.edu/packages/dods/ for more detailed
//information about DODS.
//
//A GDS may be used to provide the LIS core with the forcing and input
//parameter data needed to run an LSM.

