
[[sec_intro,Introduction]]
== Introduction

This is the Land Information System (LIS) User's Guide.  This document describes how to download and install the code and data needed to run the LIS executable for LIS revision {lisfrevision}.  It describes how to build and run the code, and finally this document also describes how to download output data-sets to use for validation.

This document consists of 12 sections, described as follows:

. *<<sec_intro>>*:
   the section you are currently reading.

. *<<sec_backgrd>>*:
   general information about the LIS project.

. *<<sec_prelim>>*:
   general information, steps, instructions, and definitions used throughout the rest of this document.

. *<<sec_obtain-src>>*:
   the steps needed to download the source code.

. *<<sec_build>>*:
   the steps needed to build the LIS executable.

. *<<sec_run>>*:
   the steps needed to prepare and submit a run, also describes the various run-time configurations.

. *<<sec_testcases>>*:
   describes the LIS test cases.

. *<<sec_postproc>>*:
   the steps needed to post-process generated output for visualization.

. *<<sec_lisconfigfile>>*:
   describes the user-configurable options.

. *<<sec_forcingvars>>*:
   describes the user-configurable input forcing variable options.

. *<<sec_modeloutputlisttable>>*:
   describes the user-configurable output variable options.

. *<<sec_usersupport>>*:
   describes how to request help from and provide feedback to the LISF development team.


=== What's New
//\attention{See _RELEASE_NOTES_ found in the _source.tar.gz_ file for more details.  (See Section <<sec_obtain-src>>.)}

==== Version 7.8

. Includes new router
* HyMAP3
. Includes new crop model
* AquaCrop v7.2
. Includes additional surface models
* SnowModel version April-2021 {emdash} for newer versions, contact Glen Liston: glen.liston@colostate.edu
. Includes new runmodes
* forecast runmode for NoahMP401 and Openwater
* RAPID ensemble mode
* ParFlow coupling for Noah and NoahMP
* NoahMP groundwater coupling through NUOPC Cap
. Supports additional metforcing datasets
* Met Office Global and Regional Ensemble Prediction System - global ensemble (MOGREPS-G) forecasts
* GALWEM radiation
* IMERG V8
. Supports additional data assmilation observation datasets
* Snow and Ice Products (SNIP) analysis
* SWOT water level observations
* Weather Satellite Follow-on Microwave (WSF-M) soil moisture

