
[[sec-lis_source_tree]]
== LIS source tree

* _LICENSES_
+
Directory the NASA Open Source license for LIS along with the licenses of other
included components

* _RESTRICTED_

* _apps_
+
Directory containing applications built on LIS

* _arch_
+
Directory containing the configurable options for building the LIS executable

* _configs_
+
Directory containing some sample LIS configuration files

* _core_
+
Directory containing core routines in LIS

* _dataassim_
+
Top level directory for data assimilation support, which includes the following subcomponents

** _algorithm_
+
Directory containing the following data assimilation algorithm implementations:

*** _di_
+
Direct insertion algorithm for data assimilation

*** _ekf_
+
NASA GMAO`'s extended Kalman filter algorithm for data assimilation

*** _enkf_
+
NASA GMAO`'s Ensemble Kalman Filter algorithm for data assimilation

*** _enkfgrace_
+
GRACE Ensemble Kalman Filter algorithm for data assimilation

*** _ensrf_
+
[red]##specifies what?##

*** _pf_
+
Particle filter algorithm for data assimilation

** _biasEstimation_
+
Directory containing the following dynamic bias estimation algorithms:

*** _gmaoBE_
+
NASA GMAO`'s dynamic bias estimation algorithm

** _obs_
+
Directory containing the following observation handlers for data assimilation:

*** _AMRE_swe_
+
AMSRE snow water equivalent retrievals in HDF4/HDFEOS format

*** _ANSA_SCF_
+
Blended snow cover fraction from the AFWA NASA snow algorithm

*** _ANSA_SNWD_
+
Snow depth retrievals from the AFWA NASA snow algorithm

*** _ANSA_SWE_
+
Snow water equivalent retrievals from the AFWA NASA snow algorithm

*** _ASCAT_TUW_
+
ASCAT (TU Wein) soil moisture

*** _ASO_SWE_
+
[red]##specifies what?##

*** _CDFS_GVF_
+
CDFS green vegetation fraction

*** _CDF_Transfer_NASA_SMAPsm_
+
[red]##specifies what?##

*** _ESACCI_sm_
+
ESACCI Essential Climate Variable product

*** _GCOMW_AMSR2L3SND_
+
AMSR2 snow depth retrievals

*** _GCOMW_AMSR2L3sm_
+
AMSR2 soil moisture retrievals

*** _GLASS_Albedo_
+
GLASS Albedo retrievals

*** _GLASS_LAI_
+
GLASS LAI retrievals

*** _GRACE_
+
GRACE soil moisture

*** _IMS_sca_
+
IMS snow cover area

*** _ISCCP_Tskin_
+
ISCCP skin temperature product in binary format

*** _LPRM_AMSREsm_
+
Soil moisture retrievals from AMSRE derived using the land parameter retrieval model (LPRM) from University of Amsterdam

*** _MCD15A2H_LAI_
+
[red]##specifies what?##

*** _MODIS_SPORT_LAI_
+
[red]##specifies what?##

*** _MODISsca_
+
MODIS snow cover area product in HDF4/HDFEOS format

*** _NASA_AMSREsm_
+
NASA AMSRE soil moisture data in binary format

*** _NASA_SMAPsm_
+
NASA SMAP soil moisture retrievals

*** _NASA_SMAPvod_
+
NASA SMAP vegetation optical depth retrievals

*** _PMW_snow_
+
PMW snow

*** _SMAP_E_OPLsm_
+
Operation Enhanced (9-km) SMAP soil moisture

*** _SMAP_NRTsm_
+
SMAP near-real time soil moisture retrievals

*** _SMMR_SNWD_
+
SMMR snow depth

*** _SMOPS_AMSR2sm_
+
SMOPS AMSR2 real time soil moisture

*** _SMOPS_ASCATsm_
+
SMOPS ASCAT A and B real time soil moisture

*** _SMOPS_SMAPsm_
+
SMOPS SMAP real time soil moisture

*** _SMOPS_SMOSsm_
+
SMOPS SMOS real time soil moisture

*** _SMOS_L2sm_
+
SMOS L2 soil moisture

*** _SMOS_NESDIS_
+
SMOS NESDIS soil moisture retrievals

*** _SMOS_NRTNN_L2sm_
+
SMOS near-real-time neural-network L2 soil moisture (SMOS NRT NN L2 SM)

*** _SNIP_
+
Snow and Ice Products (SNIP) analysis

*** _SNODAS_
+
Snow Data Assimilation System (SNODAS)

*** _SNODEP_
+
AFWA snowdepth data in Grib1 format

*** _SSMI_SNWD_
+
SSMI snow depth

*** _SWOT_WL_
+
Surface Water and Ocean Topography (SWOT) water level observations

*** _SYN_LBAND_TB_
+
Synthetic L-band brightness temperature

*** _THySM_
+
Thermal hydraulic disaggregation of soil moisture (THySM)

*** _USAFSI_
+
USAF Snow and Ice Analysis

*** _VIIRS_GVF_
+
VIIRS green vegetation fraction

*** _WUS_UCLAsnow_
+
Margulis Western US Snow Reanalysis dataset

*** _WindSat_Cband_sm_
+
C-band soil moisture retrievals from WindSat

*** _WindSat_sm_
+
X-band soil moisture retrievals from WindSat

*** _hydrowebWL_
+
hydroweb water level

*** _pildas_
+
PILDAS soil moisture observations (such as one generated from a previous LIS LSM run)

*** _simGRACE_JPL_
+
Synthetic soil moisture retrievals from GRACE

*** This directory also includes the following synthetic data handler examples:

*** _multisynsmobs_
+
Synthetic soil moisture data with multiple observation types

*** _syntheticSnowTb_
+
[red]##specifies what?##

*** _syntheticlst_
+
Synthetic land surface temperature data handler

*** _syntheticsf_
+
Synthetic streamflow data handler

*** _syntheticsm_
+
Synthetic soil moisture data handler (produced from a LIS LSM run)

*** _syntheticsnd_
+
Synthetic snow depth data handler

*** _syntheticswe_
+
Synthetic snow water equivalent data handler

*** _syntheticwl_
+
[red]##specifies what?##

** _perturb_
+
Directory containing the following perturbation algorithm implementations

*** _gmaopert_
+
NASA GMAO`'s perturbation algorithm

*** _uniform_
+
[red]##specifies what?##

* _forecast_
+
Top level directory for forecasting support, which includes the following subcomponents

** algorithm
+
Directory containing the following forecasting algorithm implementations

*** ESPboot
+
Boot ensemble streamflow prediction

*** ESPconv
+
Conventional ensemble streamflow prediction

* _interp_
+
Generic spatial and temporal interpolation routines

* _irrigation_
+
Directory containing the following irrigation schemes

** _drip_
+
Drip irrigation scheme

** _flood_
+
Flood irrigation scheme

** _sprinkler_
+
Demand sprinkler irrigation scheme

* _lib_
+
Directory contains the following RTM-related libraries

** lis-cmem3
** lis-crtm
** lis-crtm-profile-utility

* _make_
+
Directory containing Makefile and needed header files for building LIS executable

* _metforcing_
+
Top level directory for base meteorological forcing methods, which includes the following implementations

** _3B42RT_
+
TRMM 3B42RT precipitation product

** _3B42RTV7_
+
TRMM 3B42RTV7 precipitation product

** _3B42V6_
+
TRMM 3B42V6 precipitation product

** _3B42V7_
+
TRMM 3B42V7 precipitation product

** _AWAP_
+
AWAP precipitation product

** _AWRAL_
+
Australian Water Resource Assessment Landscape (AWRA-L) metforcing data

** _Bondville_
+
Bondville forcing products

** _COAMPSout_
+
Metforcing extracted from COAMPS output (COAMPSout)

** _HiMAT_GMU_
+
Downscaled MERRA2 precipitation data over the High Mountain Asia domain from GMU (HiMAT_GMU)

** _Loobos_
+
[red]##specifies what?##

** _PALSmetdata_
+
PALS station data

** _RFE2Daily_
+
RFE2 precipitation product from FEWSNET (diurnally non-disaggregated)

** _RFE2gdas_
+
RFE2 precipitation product from FEWSNET bias corrected against GDAS data

** _WRFAKdom_
+
Metforcing extracted from WRF output over Alaska domain (WRFAKdom)

** _WRFout_
+
Metforcing extracted from WRF output (WRFout)

** _WRFoutv2_
+
Metforcing extracted from WRF output (WRFoutv2)

** _agrradps_
+
AGRMET radiation product (polar stereographic prjection)

** _chirps2_
+
UCSB CHIRPS v2.0 satellite-gage merged precipitation product

** _climatology_
+
LDT-generated forcing climatologies

** _cmap_
+
CMAP precipitation product

** _cmorph_
+
CMORPH precipitation product

** _ecmwf_
+
ECMWF meteorological forcing data

** _era5_
+
[red]##specifies what?##

** _galwem_
+
GALWEM 17km or 0.25deg deterministic forecast reader

** _galwem_ge_
+
GALWEM-GE forecast reader

** _gdas_
+
NCEP GDAS meteorological forcing data

** _gdasT1534_
+
NCEP GDAS GFS T1534 meteorological forcing data

** _gddp_
+
NASA Earth Exchange Global Daily Downscaled Projections (NEX-GDDP)

** _gefs_
+
[red]##specifies what?##

** _genEnsFcst_
+
User-derived ensemble forecast data

** _genMetForc_
+
LDT-generated meteorological forcing data

** _geos5fcst_
+
NASA GEOS 5 meteorological forecast forcing data

** _geos_it_
+
GEOS-IT

** _gfs_
+
NCEP GFS meteorological forcing data

** _gldas_
+
NASA GMAO GLDAS meteorological forcing data

** _gswp1_
+
Global Soil Wetness Project-1 meteorological forcing data

** _gswp2_
+
Global Soil Wetness Project-2 meteorological forcing data

** _imerg_
+
GPM L3 precipitation product

** _merra2_
+
GMAO Modern Era Retrospective-Analysis for Research and Applications data

** _mogreps_g_
+
Met Office Global and Regional Ensemble Prediction System - global ensemble (MOGREPS-G) forecasts

** _mrms_
+
National Center for Environmental Prediction (NCEP) Multi-Radar/Multi-Sensor (MRMS) Doppler Radar+gage product.

** _nam242_
+
North American Mesoscale Forecast System (NAM) 242 AWIPS Grid \-- Over Alaska product

** _narr_
+
North American Regional Reanalysis (3d) data

** _nldas2_
+
North American Land Data Assimilation System 2 forcing product

** _pet_usgs_
+
Daily potential evapotranspiration data from the USGS FAO-PET method, using GDAS forcing fields as inputs

** _plumber2_
+
PLUMBER2 station data

** _pptEnsFcst_
+
[red]##specifies what?##

** _princeton_
+
Renalaysis product from Princeton University (<<sheffield_etal_2006>>)

** _scan_
+
Soil Climate Analysis Network precipitation product

** _snotel_
+
SNOTEL meteorological forcing data

** _stg2_
+
NCEP Stage IV QPE precipitation product

** _stg4_
+
NCEP Stage II precipitation product

** _templateMetForc_
+
An empty template for meteorological forcing data implementations

** _usaf_
+
Routines for generating meteorological forcing data in the "`AGRMET ops`" running mode and for handling said data when running in the "`retrospective`" runmode

** _vicforcing_
+
VIC 4.1.1 pre-processed meteorological forcing data

** _vicforcing.4.1.2_
+
VIC 4.1.2 pre-processed meteorological forcing data

* _offline_
+
Directory containing the main program for the offline mode of operation

* _optUE_
+
Top level directory for optimization support, which includes the following subcomponents

** _algorithm_
+
Directory containing the following optimization algorithm implementations

*** _DEMC_
+
Differential evolution Monte Carlo algorithm

*** _DEMCz_
+
Differential evolution Monte Carlo Z algorithm

*** _ES_
+
Enumerated search

*** _GA_
+
Single objective Genetic Algorithm

*** _LM_
+
Levenberg-Marquardt gradient search algorithm

*** _MCSIM_
+
Monte Carlo simple propagation scheme

*** _RWMCMC_
+
Random walk Markov chain monte carlo algorithm

*** _SCE-UA_
+
Shuffled Complex Evolutionary Algorithm

** _type_

*** _paramestim_
+
Directory for parameter estimation support
+
The directory for parameter estimation support _paramestim_ includes the following subcomponents

**** _objfunc_
+
Directory containing the following objective function evaluation methods

***** _LL_
+
Maximum likelihood

***** _LM_
+
Objective function definition for LM algorithm

***** _LS_
+
Least squares based objective function

***** _P_
+
Prior function definition

**** _obs_
+
Directory containing the following observation handlers for parameter estimation

***** _AMSRE_SR_

***** _ARM_
+
[red]##specifies what?##

***** _ARSsm_
+
[red]##specifies what?##

***** _Ameriflux_
+
In-situ observations from Ameriflux

***** _CNRS_
+
[red]##specifies what?##

***** _EmptyObs_

***** _FLUXNET_
+
[red]##specifies what?##

***** _Global_LS_data_
+
Global landslide observational data

***** _ISCCP_Tskin_
+
ISCCP land surface temperature observations

***** _ISMNsm_
+
[red]##specifies what?##

***** _LPRM_AMSREsm_
+
Soil moisture retrievals from AMSRE derived using the land parameter retrieval model (LPRM) from University of Amsterdam

***** _Macon_LS_data_
+
Macon County North Carolina landslide observational data

***** _SMAPsm_
+
SMAP soil moisture observational data

***** _UAsnow_
+
University of Arizona (UA) swe/snow depth observations

***** _USDA_ARSsm_
+
USDA Agricultural Research Service soil mositure retrievals

***** _pesynsm1_
+
Synthetic soil moisture observations

***** _template_

***** _wgPBMRsm_
+
PBMR soil moisture data for the Walnut Gulch watershed

* _params_
+
Directory containing implementations of the following land surface model parameters

** _albedo_
+
Routines for handling albedo data products

** _emissivity_
+
Routines for handling emissivity data products

** _gfrac_
+
Routines for handling green vegetation fraction data products

** _lai_
+
Routines for handling Leaf/Stem area index data products

** _roughness_
+
Routines for handling roughness data products

* _plugins_
+
Directory containing modules defining the function table registry of extensible functionalities

* _routing_
+
Directory containing routing models

** _HYMAP_router_
** _HYMAP2_router_
** _HYMAP3_router_
** _NLDAS_router_
** _RAPID_router_

* _rtms_
+
Directory containing coupling routines to the following radiative transfer models

** _CRTM_
+
Routines to handle coupling to the JCSDA Community Radiative Transfer Model

** _CRTM2_
+
Routines to handle coupling to the JCSDA Community Radiative Transfer Model, version 2

** _CRTM2EM_
+
Routines to handle coupling to the JCSDA Community Radiative Transfer Model Emissions model

** _LIS_CMEM3_
+
Community Microwave Emission Model from ECMWF

** _TauOmegaRTM_
+
Routines to handle coupling to the Tau Omega Radiative Transfer Model

* _runmodes_
+
Directory containing the following running modes in LIS

** _RTMforward_
+
Routines to manage the program flow when a forward model integration using a radiative transfer model is employed

** _agrmetmode_
+
Routines to manage the program flow in the AFWA operational mode

** _forecast_
+
Routines to manage the forecast simulation mode

** _gce_cpl_mode_
+
Routines to manage the program flow in the coupled LIS-GCE mode

** _landslide_optUE_
+
Routines to manage the program flow in combined use of landslide modeling simulations and optimization

** _nuopc_cpl_mode_
+
National Unified Operational Prediction Capability (NUOPC) coupled runmode

** _paramEstimation_
+
Routines to manage the program flow in the parameter estimation mode

** _retrospective_
+
Routines to manage the program flow in the retrospective analysis mode

** _smootherDA_
+
Routines to manage the program flow in the smoother da analysis mode

** _wrf_cpl_mode_
+
Routines to manage the program flow in the coupled LIS-WRF mode not using ESMF

* _surfacemodels_
+
Top level directory for surface model support, which includes the following subcomponents

** _glacier_
+
Directory containing implementations of the following glacier surface models

*** _noahmp.3.9.1.1_
+
NCAR Noah multiphysics land surface model version 3.9.1.1

*** _template_
+
An empty template for glacire surface model implementations

** _lake_
+
Directory containing implementations of the following lake surface models

*** _FLake.1.0_
+
FLake, version 1.0.  #For internal use only.#

** _land_
+
Directory containing implementations of the following land surface models

*** _ac.7.2_
+
KU Leuven AquaCrop, version 7.2

*** _awral.6.0.0_
+
Australian Water Resource Assessment Landscape (AWRA-L) land surface model, version 6.0.0

*** _cable_
+
CSIRO Atmosphere Biosphere Land Exchange model, version 1.4b

*** _clm2_
+
NCAR community land model, version 2.0

*** _clsm.f2.5_
+
NASA GMAO Catchment land surface model version Fortuna 2.5

*** _geowrsi.2_
+
GeoWRSI version 2

*** _hyssib_
+
NASA HySSIB land surface model

*** _jules.5.0_
+
Support for UK Met Office`'s JULES 5.0 land surface model

*** _jules.5.1_
+
Support for UK Met Office`'s JULES 5.1 land surface model

*** _jules.5.2_
+
Support for UK Met Office`'s JULES 5.2 land surface model

*** _jules.5.3_
+
Support for UK Met Office`'s JULES 5.3 land surface model

*** _jules.5.4_
+
Support for UK Met Office`'s JULES 5.4 land surface model

*** _jules.5.x_
+
Support for UK Met Office`'s JULES 5.5 (and higher) land surface model

*** _mosaic_
+
NASA Mosaic land surface model

*** _noah.2.7.1_
+
NCEP Noah land surface model version 2.7.1

*** _noah.3.2_
+
NCAR Noah land surface model version 3.2

*** _noah.3.3_
+
NCAR Noah land surface model version 3.3

*** _noah.3.6_
+
NCAR Noah land surface model version 3.6

*** _noah.3.9_
+
NCAR Noah land surface model version 3.9

*** _noahmp.3.6_
+
NCAR Noah multiphysics land surface model version 3.6

*** _noahmp.4.0.1_
+
NCAR Noah multiphysics land surface model version 4.0.1

*** _rdhm.3.5.6_
+
NOAA OHD Research Distributed Hydrologic Model version 3.5.6

*** _ruc.3.7_
+
NOAA Rapid Update Cycle model version 3.7.1

*** _summa.1.0_
+
First attempt to incorporate the Structure for Unifying Multiple Modeling Alternatives (SUMMA) into LIS.  #For internal use only.#

*** _template_
+
An empty template for land surface model implementations

*** _vic.4.1.1_
+
Variable Infiltration Capacity model from University of Washington, version 4.1.1

*** _vic.4.1.2.l_
+
Variable Infiltration Capacity model from University of Washington, version 4.1.2.l

*** _subLSM_
+
Directory containing implementations of sub land surface modeling processes.

**** _crocus.8.1_
+
Crocus 8.1 snow model

**** _snowmodel_
+
CSU/Glen Liston snowmodel, April 2021

** _openwater_
+
Directory containing implementations of the following open water surface models

*** _template_
+
An empty template for open water surface model implementations

* _testcases_
+
testcases for verifying various functionalities

* _utils_
+
Miscellaneous helpful utilities

[NOTE]
====
Each of the LSM directories under _surfacemodels/land_ contain specific plugin interfaces related to

(1) coupling to WRF and GCE models,
(2) Data assimilation instances,
(3) Irrigation instances,
(4) Parameter estimation instances,
(5) Routing instances, and
(6) Radiative transfer instances.

These routines defined for Noah land surface model version 3.3 are shown below. Note that similar routines are implemented in other LSMs.

(1) Coupling interfaces:
//**** _cpl_gce_
//+
//Routines for coupling Noah with GCE

* _cpl_wrf_noesmf_
+
Routines for coupling Noah with WRF without ESMF


(2) Data assimilation interfaces:
//**** _da_multism_
//+
//Noah routines related to the assimilation of data with
//multiple soil moisture observation types
//**** _da_scf_
//+
//Noah routines related to the assimilation of snow cover
//fraction observations

* _da_snodep_
+
Noah routines related to the assimilation of AFWA SNODEP observations

* _da_snow_
+
Noah routines related to the assimilation of snow water equivalent observations

//**** _da_snwd_
//+
//Noah routines related to the assimilation of snow depth
//observations

* _da_soilm_
+
Noah routines related to the assimilation of soil moisture observations

//**** _da_swe_
//+
//Noah routines related to the assimilation of snow water
//equivalent observations
//**** _da_tskin_
//+
//Noah routines related to the assimilation of land surface
//temperature observations

(3) Irrigation interfaces:

* _irrigation_
+
Noah routines related to interacting with the irrigation scheme

(4) Parameter estimation interfaces:

* _pe_
+
Noah routines related to the estimation of soil properties through parameter estimation

//**** _pe_soilf_ footnote:disclaimer[]
//+
//Noah routines related to the estimation of soil properties
//through parameter estimation
//**** _pe_soilp30_ footnote:disclaimer[]
//+
//Noah routines related to the estimation of soil properties
//through parameter estimation
//**** _pe_soilp5_ footnote:disclaimer[]
//+
//Noah routines related to the estimation of soil properties
//through parameter estimation
//**** _pe_soilp5ln_ footnote:disclaimer[]
//+
//Noah routines related to the estimation of soil properties
//through parameter estimation
//**** _pe_z0_ footnote:disclaimer[]
//+
//Noah routines related to the estimation of roughness length
//through parameter estimation

(5) Routing interfaces:

* _routing_
+
Noah routines related to interacting with the routing schemes

(6) Radiative transfer model interfaces:

* _sfc_cmem3_
* _sfc_crtm_
* _sfc_tauomega_
====

