
[[sec_usersupport,User Support]]
== User Support

This section describes how to request help from and provide feedback to the LISF development team.

=== Requesting Help

To request help from the LISF development team, please visit the Discussions tab of our GitHub repository at https://github.com/NASA-LIS/LISF/discussions.  Please review the existing posts; your question may already be answered.  If it is not, then please open a "`New discussion`" to post your question there.

NOTE: Posting a question requires a GitHub account. Register at https://github.com/signup.

=== Bug Reports

Please review our link:https://github.com/NASA-LIS/LISF/blob/master/CONTRIBUTING.md[Contribution Guidelines] to learn how to report a bug or error.

When reporting a bug or an error running LIS, please provide a description of the problem, including any error messages printed to the screen.  Attach a copy of the _lislog.0000_ file.  Also attach a copy of any relevant supporting files such as: +

For LIS:

* _lis.config_
* _lislog.0000_
* _MODEL_OUTPUT_LIST.TBL_
* _configure.lis_ (in your make directory)

For LDT:

* _ldt.config_
* _ldtlog.0000_
* _configure.ldt_ (in your make directory)

For LVT:

* _lvt.config_
* _lvtlog.0000_
* _configure.lvt_ (in your make directory)

[IMPORTANT]
====
Please note that the LISF development team does not receive funding to provide community support.  Your questions and issues are important to us, but we can address them only when time permits.

Due to U.S. federal law, we are not allowed to respond to anyone from a designated country (see https://www.nasa.gov/oiir/export-control). By policy, we will not respond to messages from either non-institutional or non-organizational email addresses; e.g., we will not respond to email messages from gmail.
====

