
== Test-cases
anchor:sec_testcases[Test-cases]

This section describes how to obtain and how to use the test cases provided by the LIS team.

There are two categories of testcases: public tests and internal tests.


=== Public tests

The new LIS framework (LISF) set of public testcases include a full end-to-end suite of LDT, LIS, and LVT cases that build off each other with several different steps, which are outlined in the table below. The suite of testcases include generating model parameter and assimilation-based input files using LDT, running the Noah land surface model (LSM) for a sample "open-loop" (or baseline) experiment and a data assimilation (DA) experiment using LIS, and then comparing output from the sample experiments using LVT. 

The new public test cases are available from our main LIS webpage:

{listesturl}

All required input and data files are bundled with each of the cases from the above website. Also, documentation is provided that accompanies each of the cases for additional details and information. Below the table of test cases on the webpage, users will find information about which version, compiler and libraries used to generate and test the different test cases provided. 


=== Internal tests

The main purpose of these test cases is for the LIS development team to internally test various components of the LIS source code.  These test cases are comprised of three parts: a _testcases_ sub-directory included in the LIS source code, input data, and output data.

For these test cases, we do not provide any of the input or output datasets, but users are welcome to use the config files in these subdirectory cases as a guide to setting up their own individual experiments and for their own testing purposes.

==== The _testcases_ Sub-directory
anchor:sssec_testcases[The _testcases_ Sub-directory]

The layout of the _testcases_ sub-directory matches the layout of the top-level _src_ directory.  For example, LIS contains support for processing GDAS forcing data.  These routines are in _src/metforcing/gdas_.  The test-case for GDAS is in _src/testcases/metforcing/gdas_.


These test-case sub-directories contain several files.  For example, the _src/testcases/metforcing/gdas_ test-case contains these main files:

. _README_
+
contains instructions on how to run the test-case.

. _ldt.config_
+
is the configuration file for LDT to process input parameters for the test-case.

. _lis.config_
+
is a configuration file to set the test-case.

. _MODEL_OUTPUT_LIST.TBL_
+
is a configuration file to set the output for the test-case.

. _output.ctl_
+
is a GrADS descriptor file.  This file is used with GrADS to plot the output data that you will generate when you run LIS.  You may also read this file to obtain metadata regarding the structure of the output files.  This metadata is useful in helping you plot the output using a different program.

