
[[sec_testcases,Testcases]]
== Testcases

This section describes how to obtain and how to use the testcases provided by the LISF development team.

There are two categories of testcases: public tests and internal tests.


=== Public tests

The new LIS framework (LISF) set of public testcases includes a full end-to-end suite of LDT, LIS, and LVT cases that build off each other with several different steps. The suite of testcases includes generating model parameter and assimilation-based input files using LDT, running the Noah land surface model (LSM) for a sample "open-loop" (or baseline) experiment and a data assimilation (DA) experiment using LIS, and then comparing output from the sample experiments using LVT. 

The new public testcases are available from our main LIS webpage:

{listesturl}

All required input and data files are bundled with each of the cases from the above website. Also, documentation is provided that accompanies each of the cases for additional details and information.
//Below the table of testcases on the webpage, users will find information about which version, compiler and libraries used to generate and test the different testcases provided. 


=== Internal tests

The main purpose of these testcases is for the LISF development team to internally test various components of the LIS source code.  These testcases are comprised of three parts: a _testcases_ sub-directory included in the LIS source code, input data, and output data.

For these testcases, we do not provide any of the input or output datasets, but users are welcome to use the config files in these subdirectories as a guide to setting up their own individual experiments and for their own testing purposes.

[[sssec_testcases,The _testcases_ Sub-directory]]
==== The _testcases_ Sub-directory

The layout of the _testcases_ sub-directory matches the layout of the top-level _lis_ directory.  For example, LIS contains support for processing GDAS forcing data.  These routines are in _lis/metforcing/gdas_.  The testcase for GDAS is in _lis/testcases/metforcing/gdas_.


These testcase sub-directories contain several files.  For example, the _src/testcases/metforcing/gdas_ testcase contains these main files:

. _README_
+
contains instructions on how to run the testcase.

. _ldt.config_
+
is the configuration file for LDT to process input parameters for the testcase.

. _lis.config_
+
is the configuration file for LIS to run the testcase.

. _MODEL_OUTPUT_LIST.TBL_
+
is the configuration file to set the output for the testcase.

. _output.ctl_
+
is a GrADS descriptor file.  This file is used with GrADS to plot the output data that you will generate when you run LIS.  You may also read this file to obtain metadata regarding the structure of the output files.  This metadata is useful in helping you plot the output using a different program.

