
== Development Environments

=== Supported systems

LISF and its dependencies have been compiled and run on
Linux PC (Intel/AMD based) systems,
//Cray systems,
//and IBM Power9 systems.
and Cray systems.

These instructions expect that you are using such a system.  In particular you need:

==== Linux

===== Compilers

* Intel Fortran Compiler (ifort) version 2023 with corresponding Intel C Compiler (icc) along with GNU`'s Compiler Collection version 11.2.0 or 12.1.0.
* or GNU`'s Compiler Collection version 11.2.0, both gfortran and gcc.

===== Tools

* GNU`'s make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 3.6
// On discover (May 2026)
// 4.2.1
// 5.26.1
// 3.6.5

IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

//
//      *** or Absoft's Pro Fortran Software Developement Kit, version 10.0
//            with GNU`'s C and C++ compilers, gcc and g++, version 3.3.3
//
//      *** or Lahey/Fujitsu's Fortran 95 Compiler, release L6.00c
//            with GNU`'s C and C++ compilers, gcc and g++, version 3.3.3
//

==== Cray/Linux

===== Compilers

* Intel Fortran Compiler version 2021 or 2022 with corresponding Intel C Compiler, along with GNU`'s Compiler Collection version 11.2.0 or 12.1.0.
* or Cray Compiler Environment (cce) version 15.0.0 or 19.0.0, along with GNU`'s Compiler Collection version 7.5.0 or 11.2.0.

===== Tools

* GNU`'s make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 3.6
// On narwhal (May 2026)
// 4.2.1
// 5.26.1
// 3.6.5

IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

//==== IBM/Linux
//
//===== Compilers
//
//* GNU`'s Compiler Collection version 11.0, both gfortan and gcc.
//
//===== Tools
//
//* GNU`'s make, gmake, version 3.77 or 3.81
//* Perl, version 5.10
//* Python, version 3.6
//
//IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

==== Python support

The use of Python 2.7 for building LISF is now deprecated.  If you only have Python 2.7, then edit the following four files

* ldt/make/makedep.py
* lis/make/makedep.py
* lis/make/plugins.py
* lvt/make/makedep.py

changing

```
#!/usr/bin/env python3
```

to

```
#!/usr/bin/env python
```

Future releases will depend on Python 3 only.

