
== Development Environments

=== Supported systems

LISF and its dependencies have been compiled and run on
Linux PC (Intel/AMD based) systems,
//IBM AIX systems
//SGI Altix systems
Cray systems,
and IBM Power9 systems.

These instructions expect that you are using such a system.  In particular you need:

==== Linux

===== Compilers

* Intel Fortran Compiler versions 2021 or 2022 with corresponding Intel C Compiler along with GNU`'s Compiler Collection version 11.2.0 or 12.1.0.
* or GNU`'s Compiler Collection version 11.2.0, both gfortran and gcc.

===== Tools

* GNU`'s make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 3.6

IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

//
//      *** or Absoft's Pro Fortran Software Developement Kit, version 10.0
//            with GNU`'s C and C++ compilers, gcc and g++, version 3.3.3
//
//      *** or Lahey/Fujitsu's Fortran 95 Compiler, release L6.00c
//            with GNU`'s C and C++ compilers, gcc and g++, version 3.3.3
//

==== Cray/Linux

===== Compilers

* Intel Fortran Compiler version 2021 or 2022 with corresponding Intel C Compiler, along with GNU`'s Compiler Collection version 11.2.0 or 12.1.0.
* or Cray Compiler Environment (cce) version 14.0.0, along with GNU`'s Compiler Collection version 11.2.0.

===== Tools

* GNU`'s make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 3.6

IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

==== IBM/Linux

===== Compilers

* GNU`'s Compiler Collection version 11.0, both gfortan and gcc.

===== Tools

* GNU`'s make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 3.6

IMPORTANT: The use of Python 2.7 for building LISF is now deprecated.  See Section <<Python support>>.

//
//   * IBM
//      ** XL Fortran version 10.1.0.6
//      ** GNU`'s make, gmake, version 3.77
//
//   * SGI Altix
//      ** Intel Fortran Compiler version 12
//      ** GNU`'s make, gmake, version 3.77

==== Python support

The use of Python 2.7 for building LISF is now deprecated.  If you only have Python 2.7, then edit the following four files

* ldt/make/makedep.py
* lis/make/makedep.py
* lis/make/plugins.py
* lvt/make/makedep.py

changing

```
#!/usr/bin/env python3
```

to

```
#!/usr/bin/env python
```

Future releases will depend on Python 3 only.

