
[[sec-obtain-src]]
== Obtaining the Source Code

This section describes how to obtain the source code needed to build the LVT executable.

Beginning with LIS public release 7.1rp1, the LIS and LVT source code is available as open source under the NASA Open Source Agreement (NOSA).  Please see {lisurl}[LIS`' web-site] for a copy the NOSA.

Due to the history of LVT's development, prior versions of the LVT source code may not be freely distributed. That older source code is available only to U.S. government agencies or entities with a U.S.  government grant/contract. {lisurl}[LIS`' web-site] explains how qualified persons may request a copy of the older source code.

[[sec-important_note_fs]]
=== Important Note Regarding File Systems

LVT is developed on Linux/Unix platforms. Its build process expects a case sensitive file system. Please make sure that you unpack and/or "`svn checkout`" the LVT code into a directory within a case sensitive file system. In particular, if you are using LVT within a Linux-based virtual machine hosted on a Windows or Macintosh system, do not compile/run LVT from within a shared folder. Move the LVT source code into a directory within the virtual machine.

[[sec-releasetarball]]
=== Public Release Source Code Tar File

The LVT {lisrevision} source code is available for download as a tar-file from {lisurl}[LIS`' web-site]. All users are encouraged to fill in the Registration Form and join the mailing list, both also accessible from {lisurl}[LIS`' website]. After downloading the LVT tar-file:

:sectnums!: // disable section numbers

==== Step 1

Create a directory to unpack the tar-file into. Let's call it _TOPLEVELDIR_.

==== Step 2

Place the tar-file in this directory.

[subs="attributes"]
....
% mv {lvttarball} TOPLEVELDIR
....

==== Step 3

Go into this directory.

....
% cd TOPLEVELDIR
....

==== Step 4

Unzip and untar the tar-file.

[subs="attributes"]
....
% gzip -dc  {lvttarball} | tar xf -
....

Note that the directory containing the LVT source code will be referred to as _$WORKING_ throughout the rest of this document.

:sectnums: // re-enable section numbers

[[sec-checkoutsrc]]
=== Checking Out the Source Code

The source code is maintained in a Subversion repository. Only developers may have access to the repository. Developers must use the Subversion client (`svn`) to obtain the LVT source code. If you need any help regarding Subversion, please go to {svnurl}.

Developers must first obtain access to the LVT source code respository.  To obtain access you must contact the LVT team. Once you have access to the repository, you will be given the correct Subversion command to run to checkout the source code.

:sectnums!: // disable section numbers

==== Step 1

Create a directory to checkout the code into. Let's call it _TOPLEVELDIR_.

==== Step 2

Go into this directory.

....
% cd TOPLEVELDIR
....

==== Step 3

Check out the source code into a directory called _src_.

For the public version, run the following command:

....
% svn checkout https://progress.nccs.nasa.gov/svn/lis/tools/lvt/7/public7.2 src
....

Note that the directory containing the LVT source code will be referred to as _$WORKING_ throughout the rest of this document.

:sectnums: // re-enable section numbers

Source code documentation may be found on {lisurl}[LVT's web-site]. Follow the "`Documentation`" link.

