SUBROUTINE DR_HOOK_UTIL(LDHOOK,CDNAME,KCASE,PKEY,CDFILENAME,KSIZEINFO)
IMPLICIT NONE
LOGICAL, INTENT(INOUT)      :: LDHOOK
CHARACTER(LEN=*),INTENT(IN) :: CDNAME,CDFILENAME
INTEGER,INTENT(IN) :: KCASE,KSIZEINFO
REAL,INTENT(INOUT) :: PKEY
return
END SUBROUTINE DR_HOOK_UTIL


SUBROUTINE DR_HOOK_UTIL_MULTI(LDHOOK,CDNAME,KCASE,PKEY,KPKEY,CDFILENAME,KSIZEINFO)
IMPLICIT NONE
LOGICAL,INTENT(IN)          :: LDHOOK
CHARACTER(LEN=*),INTENT(IN) :: CDNAME,CDFILENAME
INTEGER,INTENT(IN) :: KPKEY, KCASE,KSIZEINFO
REAL,INTENT(INOUT) :: PKEY(KPKEY)
return
END SUBROUTINE DR_HOOK_UTIL_MULTI
