
[[sec-build]]
== Building the Executable

This section describes how to build the source code and create LDT's executable: named LDT.

=== Development Tools

This code has been compiled and run on Linux PC (Intel/AMD based) systems
//IBM AIX systems,
//and SGI Altix systems.
and Cray systems. These instructions expect that you are using such a system. In particular you need:

==== Linux

===== Compilers

* either Intel Fortran Compiler versions 14, 15 or 16 with corresponding Intel C Compiler
* or GNU's Compiler Collection 4.9.2, both gfortran and gcc.

//      \item or Absoft's Pro Fortran Software Developement Kit, version 10.0
//            with GNU's C and C++ compilers, gcc and g++, version 3.3.3
//
//      \item or Lahey/Fujitsu's Fortran 95 Compiler, release L6.00c
//            with GNU's C and C++ compilers, gcc and g++, version 3.3.3

===== Tools

* GNU's make, gmake, version 3.77 or 3.81
* perl, version 5.10
* python, version 2.7

==== Cray/Linux

===== Compilers

* Intel Fortran Compiler versions 14, 15, or 16 with corresponding Intel C Compiler

===== Tools

* GNU's make, gmake, version 3.77 or 3.81
* perl, version 5.10
* python, version 2.7

//
//   * IBM
//      ** XL Fortran version 10.1.0.6
//      ** GNU's make, gmake, version 3.77
//
//   * SGI Altix
//      ** Intel Fortran Compiler version 12
//      ** GNU's make, gmake, version 3.77

[[ssec-requiredlibs]]
=== Required Software Libraries

In order to build the LDT executable, the following libraries must be installed on your system:

==== Earth System Modeling Framework (ESMF) version 5.2.0rp3 (or higher)

(http://www.earthsystemmodeling.org/download/releases.shtml)

//
//         Please read the ESMF User's Guide for details on installing
//         ESMF with MPI support and without MPI support (``mpiuni'').
//

Note that starting with ESMF version 5, the ESMF development team is trying to maintain backwards compatibility with its subsequent releases.  The LDT development team, however, has neither compiled nor tested against versions of ESMF newer than 5.2.0rp3.

==== JasPer version 1.900.1

(http://www.ece.uvic.ca/{tilde}frodo/jasper/)

Note that when running the `configure` command you must include the `--enable-shared` option.

==== GRIB-API version 1.12.3 (or higher)

(https://software.ecmwf.int/wiki/display/GRIB/Home)

==== NetCDF either version 3.6.3 or version 4.3.0 (or higher)

(http://www.unidata.ucar.edu/software/netcdf/)


Please read the on-line documentation for details on installing NetCDF.

===== Addtional notes for NetCDF 4:

You must also choose whether to compile with compression enabled.  Compiling with compression enabled requires HDF 5 and zlib libraries. To enable compression, add `--enable-netcdf-4` to the `configure` options. To disable compression, add `--disable-netcdf-4` to the `configure` options.

An example of installing NetCDF 4 without compression:
....
% ./configure --prefix=$HOME/local/netcdf-4.3.0 --disable-netcdf-4
% gmake
% gmake install
....

An example of installing NetCDF 4 with compression:
....
% CPPFLAGS=-I$HOME/local/hdf5/1.8.11/include \
> LDFLAGS=-L$HOME/local/hdf5/1.8.11/lib \
> ./configure --prefix=$HOME/local/netcdf/4.3.0 --enable-netcdf-4
% gmake
% gmake install
....

You must also download the _netcdf-fortran-4.2.tar.gz_ file. First install the NetCDF C library, then install the NetCDF Fortran library. Again, please read the on-line documentation for more details.

An example of installing the NetCDF 4 Fortran library:
....
% LD_LIBRARY_PATH=$HOME/local/netcdf/4.3.0/lib:$LD_LIBRARY_PATH \
> CPPFLAGS=-I$HOME/local/netcdf/4.3.0/include \
> LDFLAGS=-L$HOME/local/netcdf/4.3.0/lib \
> ./configure --prefix=$HOME/local/netcdf/4.3.0
% gmake
% gmake install
....

=== Optional Software Libraries

The following libraries are not required to compile LDT. They are used to extend the functionality of LDT.

//   * Message Passing Interface (MPI)
//
//         If you wish to run LDT with multiple processes (i.e., in
//         parallel), then you must install an MPI library package.
//
//            ** vendor supplied (e.g., Intel MPI) or
//            ** MPICH version 1.2.7p1
//               (http://www-unix.mcs.anl.gov/mpi/mpich1/)
//            ** Open MPI
//               (http://www.open-mpi.org/)
//
//         Note that LDT does not support OpenMP style parallelization.
//         There is some experimental support within LDT, but you should
//         not enable it.

==== HDF

You may choose either HDF version 4, HDF version 5, or both.

HDF is used to support a number of remote sensing datasets.

If you wish to use MODIS snow cover area observations or NASA AMSR-E soil moisture observations, then you need HDF 4 support.

If you wish to use ANSA snow cover fraction observations, then you need HDF 5 support.

If you wish to use PMW snow observations, then you need both HDF 4 and HDF 5 support.

===== HDF 4

If you choose to have HDF version 4 support, please download the HDF source for version 4.2r4 (or later) from (http://www.hdfgroup.org/products/hdf4) and compile the source to generate the HDF library. Make sure that you configure the build process to include the Fortran interfaces by adding the `--enable-fortran` option to the `configure` command.

Note that HDF4 contains its own embedded version of NetCDF. You must disable this support by adding the `--disable-netcdf` option to the `configure` command.

Note that when compiling LDT with HDF 4 support, you must also download and compile HDF-EOS2 (http://hdfeos.org/).

===== HDF 5

If you choose to have HDF version 5 support, please download the HDF source for version 1.8.11 (or later) from (http://www.hdfgroup.org/HDF5/) and compile the source to generate the HDF library. Make sure that you configure the build process to include the Fortran interfaces by adding the `--enable-fortran` option to the `configure` command.

//Note that when compiling LDT with HDF 5 support, you must also
//download and compile HDF-EOS5
//\hyperref{http://hdfeos.org/}{}{}{(http://hdfeos.org/)}.

==== Notes

To install these libraries, follow the instructions provided at the various URL listed above. These optional libraries have their own dependencies, which should be documented in their respective documentation.

//If not, review the appropriate
//\file{\$WORKING/arch/configure.ldt.*} file for some hints regarding
//additional low level libraries needed for linking.
//
//Note that due to an issue involving multiple definitions within the NetCDF 3
//and HDF 4 libraries, you cannot compile LDT with support for both
//NetCDF 3 and HDF 4 together.

Note that due to the mix of programing languages (Fortran and C) used by LDT, you may run into linking errors when building the LDT executable.  This is often due to (1) the Fortran compiler and the C compiler using different cases (upper case vs. lower case) for external names, and (2) the Fortran compiler and C compiler using a different number of underscores for external names.

When compiling code using Absoft's Pro Fortran SDK, set the following compiler options:

....
-YEXT_NAMES=LCS -s -YEXT_SFX=_ -YCFRL=1
....

These must be set for each of the above libraries.

=== Build Instructions

:sectnums!: // disable section numbers

==== Step 1

Perform the steps described in Section <<sec-obtain-src>> to obtain the source code.

==== Step 2

Goto the _$WORKING_ directory. This directory contains two scripts for building the LDT executable: _configure_ and _compile_.

==== Step 3

Set the LDT_ARCH environment variable based on the system you are using. The following commands are written using Bash shell syntax.

.For a Linux system with the Intel Fortran compiler
....
% export LDT_ARCH=linux_ifc
....

//.For an AIX system
//....
//% export LDT_ARCH=AIX
//....

//.For a Linux system with the Absoft Fortran compiler
//....
//% export LDT_ARCH=linux_absoft
//....

//.For a Linux system with the Lahey Fortran compiler
//....
//% export LDT_ARCH=linux_lf95
//....

It is suggested that you place this command in your _.profile_ (or equivalent) startup file.

==== Step 4

Run the script first by typing:

....
% ./configure
....

This script will prompt the user with a series of questions regarding support to compile into LDT, requiring the user to specify the locations of the required and optional libraries via several LDT specific environment variables. The following environment variables are used by LDT.

[cols="<,<,<",]
|===
| Variable        | Description                | Usage

| `LDT_FC`        | Fortran 90 compiler        | required
| `LDT_CC`        | C compiler                 | required
| `LDT_MODESMF`   | path to ESMF module files  | required
| `LDT_LIBESMF`   | path to ESMF library files | required
| `LDT_JASPER`    | path to JasPer library     | required
| `LDT_GRIBAPI`   | path to GRIB-API library   | required
| `LDT_NETCDF`    | path to NetCDF library     | required
| `LDT_HDF4`      | path to HDF4 library       | optional
| `LDT_HDF5`      | path to HDF5 library       | optional
| `LDT_HDFEOS`    | path to HDFEOS library     | optional
//| `LDT_MINPACK`   | path to MINPACK library    | optional
//| `LDT_CRTM`      | path to CRTM library       | optional
//| `LDT_CRTM_PROF` | path to CRTM Prof library  | optional
//| `LDT_CMEM`      | path to CMEM library       | optional
|===

//{cpp} is C++
Note that the variable `CC` must be set to a C compiler, not a {cpp} compiler.  A {cpp} compiler may mangle internal names in a manner that is not consistent with the Fortran compiler. This will cause errors during linking.

It is suggested that you add these definitions to your _.profile_ (or equivalent) startup file.

You may encounter errors either when trying to compile LDT or when trying to run LDT because the compiler or operating system cannot find these libraries. To fix this, you must add these libraries to your `$LD_LIBRARY_PATH` environment variable. For example, say that you are using ESMF, GRIB-API, NetCDF, and HDF5. Then you must execute the following command (written using Bash shell syntax):

....
% export LD_LIBRARY_PATH=$LDT_HDF5/lib:$LDT_LIBESMF:$LDT_NETCDF/lib:$LDT_GRIBAPI/lib:$LD_LIBRARY_PATH
....

It is also suggested that you add this command to your _.profile_ (or equivalent) startup file.

===== Example

An example execution of the configure script is shown below:

....
% ./configure
------------------------------------------------------------------------
Setting up configuration for LDT version 7.2...
Parallelism (0-serial, 1-dmpar, default=0):
Optimization level (-2=strict checks, -1=debug, 0,1,2,3, default=2):
Assume little/big_endian data format (1-little, 2-big, default=2):
NETCDF version (3 or 4, default=4)?:
NETCDF use shuffle filter? (1-yes, 0-no, default = 1):
NETCDF use deflate filter? (1-yes, 0-no, default = 1):
NETCDF use deflate level? (1 to 9-yes, 0-no, default = 9):
Use HDF4? (1-yes, 0-no, default=1):
Use HDF5? (1-yes, 0-no, default=1):
Use HDFEOS? (1-yes, 0-no, default=1):
Include date/time stamp history? (1-yes, 0-no, default=1):
-----------------------------------------------------
 configure.ldt file generated successfully
-----------------------------------------------------
Settings are written to configure.ldt in the make directory.
If you wish to change settings, please edit that file.
To compile, run the compile script.
------------------------------------------------------------------------
....

At each prompt, select the desired value. If you desire the default value, then you may simply press the Enter key.

Most of the configure options are be self-explanatory. Here are a few specific notes:

* for `Parallelism (0-serial, 1-dmpar, default=1):`, dmpar refers to enabling MPI

//*for `Use openMP parallelism (1-yes, 0-no, default=0):`,
//select the default value of 0.  OpenMP support is
//experimental.  *Please do not use.*

* for `Assume little/big_endian data format (1-little, 2-big, default=2):`, select the default value of 2. By default, LDT reads and writes binary data in the big endian format. Only select the value of 1, if you have reformatted all required binary data into the little endian format.

ifdef::devonly[]
* for `Enable GeoTIFF support? (1-yes, 0-no, default=1):`, select 0, unless you have installed the GDAL library and have set the LDT_GDAL environment variable.
endif::devonly[]

Note that due to an issue involving multiple definitions within the NetCDF 3 and HDF 4 libraries, you cannot compile LDT with support for both NetCDF 3 and HDF 4 together.

Note that if you compiled NetCDF 4 without compression, then when specifying `NETCDF version (3 or 4, default=4):`, select `3`. Then you must manually append `-lnetcdff` to the `LDFLAGS` variable in the _make/configure.ldt_ file.

==== Step 5

Compile the LDT source code by running the _compile_ script.

....
% ./compile
....

This script will compile the libraries provided with LDT, the dependency generator and then the LDT source code. The executable _LDT_ will be placed in the _$WORKING_ directory upon successful completion of the _compile_ script.

==== Step 6

Finally, copy the _LDT_ executable into your running directory, _$RUNNING_.

:sectnums: // re-enable section numbers

=== Generating documentation

LDT code uses the ProTex (http://gmao.gsfc.nasa.gov/software/protex/) documenting system  <<protex>>.  The documentation in LaTeX format can be produced by using the `doc.csh` in the _$WORKING/utils_ directory. This command produces documentation, generating a number of LaTeX files. 
//These files can be easily converted to pdf
//or html formats using utilites such as \cmdfont{pdflatex} or
//\cmdfont{latex2html}.
These files can be easily converted to pdf using utilites such as `pdflatex`.

