
[[sec-obtain-src]]
== Obtaining the Source Code

This section describes how to obtain the source code needed to build the LDT executable.

Beginning with Land Information System Framework (LISF) public release 7.3, the LDT source code is available as open source under the Apache License, version 2.0.  Please see {apachelicense}[Apache`'s web-site] for a copy of the license.

From LDT public release 7.1rp1 through 7.2, the LDT source code is available as open source under the NASA Open Source Agreement (NOSA).  Please see {lisfurl}[LISF`'s web-site] for a copy of the NOSA.

Due to the history of LDT`'s development, versions of the LDT source code prior to 7.1rp1 may not be freely distributed.  Older source code is available only to U.S. government agencies or entities with a U.S. government grant/contract.  {lisfurl}[LISF`'s web-site] explains how qualified persons may request a copy of older source code.

NOTE: All users are encouraged to go to {lisfurl}[LISF`'s web-site] to fill in the Registration Form and join the mailing list.

[[sec-important_note_fs]]
=== Important Note Regarding File Systems

LDT is developed on Linux/Unix platforms.  Its build process expects a case sensitive file system.  Please make sure that you unpack and/or `git clone` the LDT code into a directory within a case sensitive file system.  In particular, if you are using LDT within a Linux-based virtual machine hosted on a Windows or Macintosh system, do not compile/run LDT from within a shared folder.  Move the LDT source code into a directory within the virtual machine.

[[sec_publicrelease,Public Release Source Code]]
=== Public Release Source Code

The LDT public release {lisfrevision} source code is available both on {lisfurl}[LISF`'s web-site] under the "`Source`" menu and on GitHub under the NASA-LIS organization at {nasalisf} under the "`Releases`" link.

After downloading the LISF tar-file:

:sectnums!: // disable section numbers

==== Step 1

Create a directory to unpack the tar-file into.  Let`'s call it _TOPLEVELDIR_.


==== Step 2

Place the tar-file in this directory.

[subs="attributes"]
....
% mv {ldttarball} TOPLEVELDIR
....


==== Step 3

Go into this directory.

....
% cd TOPLEVELDIR
....


==== Step 4

Unzip and untar the tar-file.

[subs="attributes"]
....
% gzip -dc {ldttarball} | tar xf -
....

:sectnums: // re-enable section numbers

[[sec-checkoutsrc]]
=== master branch

The LDT source code is maintained in a git repository hosted on GitHub.  If you wish to work with the latest development code (in the master branch), then you must use the `git` client to obtain the LDT source code.  If you need any help regarding `git` or GitHub, please go to {githuburl}.

:sectnums!: // disable section numbers

==== Step 1

Create a directory to clone the code into. Let's call it _TOPLEVELDIR_.

==== Step 2

Go into this directory.

....
% cd TOPLEVELDIR
....

==== Step 3

Clone the master branch.

[subs="attributes"]
....
% git clone {nasalisf}
....

:sectnums: // re-enable section numbers

=== Source files

Unpacking or cloning the LISF source code (according to the instructions in Section <<sec-obtain-src>>) will create a directory named _LISF_.  The LDT specific source code is in _LISF/ldt_.

NOTE: The directory containing the LDT source code, _LISF/ldt_, will be referred to as _$WORKING_ throughout the rest of this document.

=== Documentation

Processed documentation may be found on {lisfurl}[LISF`'s web-site] under the "`Docs`" menu.

