#==============================================================================
#
# Makefile for Atmospheric_Properties_Test
#
# $Id: Makefile 1960 2008-03-18 17:26:10Z paul.vandelst@noaa.gov $
#==============================================================================

# Define the executable file
EXE_FILE = Atmospheric_Properties_Test

# include the common test make components
include ../make.common

# The run target
run: all
	$(EXE_FILE)

# include the dependency list
include make.dependencies
