
[[sec-build]]
== Building the Executable

This section describes how to build the source code and create LVT`'s executable: named LVT.

Please see Section <<sec-important_note_fs>> for information regarding using a case sensitve file system for compiling/running LVT.

=== Development Tools

This code has been compiled and run on
Linux PC (Intel/AMD based) systems
//IBM AIX systems,
//and SGI Altix systems.
and Cray systems.
These instructions expect that you are using such a system.  In particular you need:

==== Linux

===== Compilers

* Intel Fortran Compiler versions 18, 19, or 20 with corresponding Intel C Compiler along with GNU's Compiler Collection version 9.2.0
* or GNU's Compiler Collection version 4.9.2 or 7.3, both gfortran and gcc.

===== Tools

* GNU's make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 2.7 or 3.8

IMPORTANT: Support for Python 2.7 is now deprecated.  Future releases will depend on Python 3.

//
//      *** or Absoft's Pro Fortran Software Developement Kit, version 10.0
//            with GNU's C and C++ compilers, gcc and g++, version 3.3.3
//
//      *** or Lahey/Fujitsu's Fortran 95 Compiler, release L6.00c
//            with GNU's C and C++ compilers, gcc and g++, version 3.3.3
//

==== Cray/Linux

===== Compilers

* Intel Fortran Compiler version 18 or 19 with corresponding Intel C Compiler, along with GNU's Compiler Collection version 7.3.0

===== Tools

* GNU's make, gmake, version 3.77 or 3.81
* Perl, version 5.10
* Python, version 2.7 or 3.8

IMPORTANT: Support for Python 2.7 is now deprecated.  Future releases will depend on Python 3.

//
//   * IBM
//      ** XL Fortran version 10.1.0.6
//      ** GNU's make, gmake, version 3.77
//
//   * SGI Altix
//      ** Intel Fortran Compiler version 12
//      ** GNU's make, gmake, version 3.77

[[ssec-requiredlibs]]
=== Required Software Libraries

In order to build the LVT executable, the following libraries must be installed on your system:

==== Earth System Modeling Framework (ESMF) version 7.1.0r (or higher)

(https://earthsystemmodeling.org/)

//
//         Please read the ESMF User's Guide for details on installing
//         ESMF with MPI support and without MPI support (``mpiuni'').
//

//==== JasPer version 2.0.14 (or higher)
//
//(http://www.ece.uvic.ca/{tilde}frodo/jasper/)
//
//Note that when running the `configure` command you must include the `--enable-shared` option.

==== OpenJPEG version 2.3.0 (or higher)

(http://www.openjpeg.org/)

==== ecCodes version 2.7.0 (or higher)

(https://confluence.ecmwf.int/display/ECC)

=== Optional Software Libraries

The following libraries are not required to compile LVT. They are used to extend the functionality of LVT.

// ==== Message Passing Interface (MPI)
//
// If you wish to run LIS with multiple processes (i.e., in parallel), then you must install an MPI library package.
//
// * vendor supplied (e.g., Intel MPI)
// // * MPICH version 1.2.7p1 (http://www-unix.mcs.anl.gov/mpi/mpich1/)
// * Open MPI (http://www.open-mpi.org/)
//
// Note that LIS does not support OpenMP style parallelization.  There is some experimental support within LIS, but you should not enable it.

==== NetCDF either version 3.6.3 or version 4.5.0 (or higher)

(http://www.unidata.ucar.edu/software/netcdf)

Please read the on-line documentation for details on installing NetCDF.

===== Additional notes for NetCDF 4:

You must also choose whether to compile with compression enabled.  Compiling with compression enabled requires HDF 5 and zlib libraries.  To enable compression, add `--enable-netcdf-4` to the `configure` options.  To disable compression, add `--disable-netcdf-4` to the `configure` options.

An example of installing NetCDF 4 without compression:

....
% ./configure --prefix=$HOME/local/netcdf-4.5.0 --disable-netcdf-4
% gmake
% gmake install
....

An example of installing NetCDF 4 with compression:

....
% CPPFLAGS=-I$HOME/local/hdf5/1.10.1/include \
> LDFLAGS=-L$HOME/local/hdf5/1.10.1/lib \
> ./configure --prefix=$HOME/local/netcdf/4.5.0 --enable-netcdf-4
% gmake
% gmake install
....

You must also download the _netcdf-fortran-4.4.4.tar.gz_ file.  First install the NetCDF C library, then install the NetCDF Fortran library.  Again, please read the on-line documentation for more details.

An example of installing the NetCDF 4 Fortran library:

....
% LD_LIBRARY_PATH=$HOME/local/netcdf/4.5.0/lib:$LD_LIBRARY_PATH \
> CPPFLAGS=-I$HOME/local/netcdf/4.5.0/include \
> LDFLAGS=-L$HOME/local/netcdf/4.5.0/lib \
> ./configure --prefix=$HOME/local/netcdf/4.5.0
% gmake
% gmake install
....

==== HDF

You may choose either HDF version 4, HDF version 5, or both.

HDF is used to support a number of remote sensing datasets.

If you wish to use MODIS snow cover area observations or NASA AMSR-E soil moisture observations, then you need HDF 4 support.

If you wish to use ANSA snow cover fraction observations, then you need HDF 5 support.

If you wish to use PMW snow observations, then you need both HDF 4 and HDF 5 support.

===== HDF 4

If you choose to have HDF version 4 support, please download the HDF source for version 4.2.13 (or higher) from https://portal.hdfgroup.org/display/support/Download+HDF4 and compile the source to generate the HDF library.  Make sure that you configure the build process to include the Fortran interfaces by adding the `--enable-fortran` option to the `configure` command.

Note that HDF4 contains its own embedded version of NetCDF.  You must disable this support by adding the `--disable-netcdf` option to the `configure` command.

IMPORTANT: When compiling LVT with HDF 4 support, you must also download and compile HDF-EOS2 version 2.19v1.00 or higher from http://hdfeos.org/software/library.php.

===== HDF 5

If you choose to have HDF version 5 support, please download the HDF source for version 1.10.1 (or higher) from http://www.hdfgroup.org/HDF5/ and compile the source to generate the HDF library.  Make sure that you configure the build process to include the Fortran interfaces by adding the `--enable-fortran` option to the `configure` command.

//Note that when compiling LVT with HDF 5 support, you must also
//download and compile HDF-EOS5 from http://hdfeos.org/.

==== GDAL version 2.4.1 (or higher)

(https://gdal.org)

IMPORTANT: When compiling LVT with GDAL support, you must also download and compile FortranGIS version 2.4 (or higher) from http://fortrangis.sourceforge.net.

==== Notes

To install these libraries, follow the instructions provided at the various URL listed above. These optional libraries have their own dependencies, which should be documented in their respective documentation.

Please note that your system may have several different compilers installed.  You must verify that you are building these libraries with the correct compiler.  You should review the output from the `configure`, `make`, etc. commands.  If the wrong compiler is being used, you may have to correct your `$PATH` environment variable, or set the `$CC` and `$FC` environment variables, or pass additional settings to the `configure` scripts.  Please consult the installation instructions provided at the various URL listed above for each library.

//If not, review the appropriate _$WORKING/arch/configure.lvt.*_ file
//for some hints regarding additional low level libraries needed for
//linking.

//Note that due to an issue involving multiple definitions within the NetCDF 3
//and HDF 4 libraries, you cannot compile LVT with support for both
//NetCDF 3 and HDF 4 together.

Note that due to the mix of programing languages (Fortran and C) used by LVT, you may run into linking errors when building the LVT executable.  This is often due to (1) the Fortran compiler and the C compiler using different cases (upper case vs. lower case) for external names, and (2) the Fortran compiler and C compiler using a different number of underscores for external names.

//When compiling code using Absoft's Pro Fortran SDK, set the following compiler options:
//
//....
//-YEXT_NAMES=LCS -s -YEXT_SFX=_ -YCFRL=1
//....
//
//These must be set for each of the above libraries.

=== Build Instructions

:sectnums!: // disable section numbers

==== Step 1

Perform the steps described in Section <<sec-obtain-src>> to obtain the source code.

==== Step 2

Goto the _$WORKING_ directory.  This directory contains two scripts for building the LVT executable: _configure_ and _compile_.

==== Step 3

Set the LVT_ARCH environment variable based on the system you are using.  The following commands are written using Bash shell syntax.

.For a Linux system with the Intel Fortran compiler
....
% export LVT_ARCH=linux_ifc
....

.For a Linux system with the GNU Fortran compiler
....
% export LVT_ARCH=linux_gfortran
....

//.For an AIX system
//....
//% export LVT_ARCH=AIX
//....

//.For a Linux system with the Absoft Fortran compiler
//....
//% export LVT_ARCH=linux_absoft
//....

//.For a Linux system with the Lahey Fortran compiler
//....
//% export LVT_ARCH=linux_lf95
//....

It is suggested that you place this command in your _.profile_ (or equivalent) startup file.

==== Step 4

Run the _configure_ script first by typing:

....
% ./configure
....

This script will prompt the user with a series of questions regarding support to compile into LVT, requiring the user to specify the locations of the required and optional libraries via several LVT specific environment variables.  The following environment variables are used by LVT.

[cols="<,<,<",]
|===
| Variable         | Description                | Usage

| `LVT_FC`         | Fortran 90                 | required
| `LVT_CC`         | C compiler                 | required
| `LVT_MODESMF`    | path to ESMF modules files | required
| `LVT_LIBESMF`    | path to ESMF library files | required
| `LVT_OPENJPEG`   | path to openJPEG library   | required
| `LVT_ECCODES`    | path to ecCodes library    | required
| `LVT_NETCDF`     | path to NETCDF library     | optional
| `LVT_HDF4`       | path to HDF4 library       | optional
| `LVT_HDF5`       | path to HDF5 library       | optional
| `LVT_HDFEOS`     | path to HDFEOS2 library    | optional
| `LVT_GDAL`       | path to GDAL library       | optional
| `LVT_FORTRANGIS` | path to FortranGIS library | optional (required by GDAL)
|===

//{cpp} is C++
Note that the `CC` variable must be set to a C compiler, not a {cpp} compiler.  A {cpp} compiler may mangle internal names in a manner that is not consistent with the Fortran compiler.  This will cause errors during linking.

It is suggested that you add these definitions to your _.profile_ (or equivalent) startup file.

You may encounter errors either when trying to compile LVT or when trying to run LVT because the compiler or operating system cannot find these libraries.  To fix this, you must add these libraries to your `$LD_LIBRARY_PATH` environment variable.
For example, say that you are using ESMF, ecCodes, NetCDF, and HDF5.  Then you must execute the following command (written using Bash shell syntax):

....
% export LD_LIBRARY_PATH=$LVT_HDF5/lib:$LVT_LIBESMF:$LVT_NETCDF/lib:$LVT_ECCODES/lib:$LD_LIBRARY_PATH
....

It is also suggested that you add this command to your _.profile_ (or equivalent) startup file.

===== Example

An example execution of the configure script is shown below:

[subs="attributes,quotes"]
....
% ./configure
------------------------------------------------------------------------
Setting up configuration for LVT
Optimization level (-3=strict checks with warnings, -2=strict checks, -1=debug, 0,1,2,3, default=2):
Assume little/big_endian data format (1-little, 2-big, default=2):
Use GRIBAPI/ECCODES? (1-gribapi, 2-eccodes, default=2):
Use NETCDF? (1-yes, 0-no, default=1):
NETCDF version (3 or 4, default=4):
NETCDF use shuffle filter? (1-yes, 0-no, default = 1):
NETCDF use deflate filter? (1-yes, 0-no, default = 1):
NETCDF use deflate level? (1 to 9-yes, 0-no, default = 9):
Use HDF4? (1-yes, 0-no, default=1):
Use HDF5? (1-yes, 0-no, default=1):
Use HDFEOS? (1-yes, 0-no, default=1):
Enable AFWA-specific grib configuration settings? (1-yes, 0-no, default=0):
Enable GeoTIFF support? (1-yes, 0-no, default=1):
Use MATLAB support? (1-yes, 0-no, default=0):
-----------------------------------------------------
 configure.lvt file generated successfully
-----------------------------------------------------
Settings are written to configure.lvt in the make directory.
If you wish to change settings, please edit that file.

To compile, run the compile script.
------------------------------------------------------------------------
....

At each prompt, select the desired value.  If you desire the default value, then you may simply press the Enter key.

Most of the configure options are be self-explanatory.  Here are a few specific notes:

//* for `Parallelism (0-serial, 1-dmpar, default=1):`,
//dmpar refers to enabling MPI

//* for `Use openMP parallelism (1-yes, 0-no, default=0):`,
//select the default value of 0.  OpenMP support is
//experimental.  Please do not use.

* for `Optimization level (-3=strict checks with warnings, -2=strict checks, -1=debug, 0,1,2,3, default=2):`
+
[IMPORTANT]
====
There is an open issue regarding compiling LVT with the GNU compilers version 7.3 (and higher).  One of the modules takes a long time to compile, and the compilation consumes a lot of memory, often to the point of aborting.

When using the GNU compilers, you should select `0`.
====

* for `Assume little/big_endian data format (1-little, 2-big, default=2):`,
select the default value of 2.  By default, LVT reads and writes binary data in the big endian format.  Only select the value of 1, if you have reformatted all required binary data into the little endian format.

* for `Use GRIBAPI/ECCODES? (1-gribapi, 2-eccodes, default=2):`,
select the default value of 2.  Technically, GRIB support is not required by LVT; however, most of the commonly used met forcing data are in GRIB, making GRIB support a practical requirement.  ecCodes is ECMWF's replacement to their GRIB-API library.  GRIB-API is supported only for historical reasons; thus, please use ecCodes.
+
IMPORTANT: GRIB-API support is now deprecated.  Future releases will support only ecCodes.

* for `Enable GeoTIFF support? (1-yes, 0-no, default=1):`,
GeoTIFF means the GeoTIFF support provided by the GDAL library.

Note that due to an issue involving multiple definitions within the NetCDF 3 and HDF 4 libraries, you cannot compile LVT with support for both NetCDF 3 and HDF 4 together.

Note that if you compiled NetCDF 4 without compression, then when specifying `NETCDF version (3 or 4, default=4):`, select 3. Then you must manually append `-lnetcdff` to the `LDFLAGS` variable in the _make/configure.lvt_ file.

==== Step 5

Compile the LVT source code by running the _compile_ script.

....
% ./compile
....

This script will compile the libraries provided with LVT, the dependency generator and then the LVT source code. The executable _LVT_ will be placed in the _$WORKING_ directory upon successful completion of the _compile_ script.

==== Step 6

Finally, copy the _LVT_ executable into your running directory, _$RUNNING_.  (See Section <<sec-run>>.)

:sectnums: // re-enable section numbers

//=== Generating documentation
//
//LVT code uses the ProTex (http://gmao.gsfc.nasa.gov/software/protex/) documenting system  <<protex>>.  The documentation in LaTeX format can be produced by using the `doc.csh` in the _$WORKING/src/utils_ directory. This command produces documentation, generating a number of LaTeX files.
// //These files can be easily converted to pdf
// //or html formats using utilites such as \cmdfont{pdflatex} or
// //\cmdfont{latex2html}.
//These files can be easily converted to pdf using utilites such as `pdflatex`.

