
// This is the MODEL_OUTPUT_LIST.TBL file.  It contains the
// user-configurable options plus documentation for generating output.
//
// Please add any updates to the LIS code regarding configuration options
// to this file -- including documentation.
//
//
// To include this file in the User's Guide:
// 1) Checkout the latest copy of this file from the repository.
// 2) Place it with the source for the User's Guide.
// 3) Rename it MODEL_OUTPUT_LIST.TBL.adoc
//


== Model Output Specifications
anchor:sec_modeloutputlisttable[Model Output Specifications]

This section defines the specification of the model output from LIS.
This file is specified in a space delimited column format.
Each row consists of the following entries:

`Short Name` specifies the ALMA compliant short name of the
variable.

`Use option` specifies whether to write the variable.
Acceptable values are:

|====
|Value | Description

|0     | do not write the variable
|1     | write the variable
|====

`Units:` specifies the desired units of the output variable.
You must check the source code to determine all the units
that are available for each output variable.

`Sign Convention:` specifies the direction in which the variable is
considered to have positive values. Note that the land models
in LIS employ the "traditional approach" where all variables
are considered positive in their dominant direction.
i.e. precipitation and radiation are positive towards the
surface (downward), evaporation, sensible heat and runoff
are positive away from the surface.

Acceptable values are:

|====
|Value |     | Description

|-     |     | No sign
|UP    | DN  | Up or Down (Used for fluxes, Precip)
|IN    | OUT | In or Out of the grid cell (Used for runoff, baseflow)
|INC   | DEC | Increase or Decrease (Used for change in storager terms)
|S2L   | L2S | Solid to Liquid and Liquid to Solid (for phase change terms)
|S2V   | V2S | Solid to Vapor and Vapor to Solid (for phase change terms)
|E     | N   | Eastward and Northward (used for Wind components)
|====

`Time Average option` determines how temporally process the
variable.
Acceptable values are:

|====
|Value | Description

|0     | Instantaneous output
|1     | Time averaged output
|2     | Instantaneous and Time averaged output
|3     | Accumulated output
|====

`Min/Max option` determines whether to record minimum and
maximum values for the variable.  For a given grid-cell, the minimum
and maximum values correspond to the minimum and maximum found 
for all subgrid tiles and ensembles contained in the grid-cell
during that output interval.
Acceptable values are:

|====
|Value | Description

|0     | Do not compute minimum and maximum values
|1     | Do compute minimum and maximum values
|====

`Standard Deviation option` determines whether to record
the standard deviation of the values for the variable.
For a given grid-cell, the standard deviation is a measure of the
spread of the subgrid tiles and ensembles contained within the
grid-cell from the grid-cell's mean.
Acceptable values are:

|====
|Value | Description

|0     | Do not compute standard deviation
|1     | Do compute standard deviation
|====

`Number of vertical levels` specifies the number of vertical levels
corresponding to the variable.

`grib ID` specifies the grib ID to be used for the variable when
output is written in grib1 format.

`grib scale factor` specifies the grib scale factor to be used for
the variable when output is written in grib1 format.

Note that this is a full list of output variables.  Not all models
support all these variables.  You must check the source code to
verify that the model you want to run supports the variables that
you want to write.
\footnotesize


....
#short_name select? units signconv timeavg? min/max? std? vert.levels grib_id grib_scalefactor longname

#Energy balance components
Swnet:        1  W/m2    DN   1 0 0 1 111 10      # Net shortwave radiation (W/m2)
Lwnet:        1  W/m2    DN   1 0 0 1 112 10      # Net longwave radiation (W/m2)
Qle:          1  W/m2    UP   1 0 0 1 121 10      # Latent heat flux (W/m2)
Qh:           1  W/m2    UP   1 0 0 1 122 10      # Sensible heat flux (W/m2)
Qg:           1  W/m2    DN   1 0 0 1 155 10      # Ground heat flux (W/m2)
Qf:           0  W/m2    S2L  1 0 0 1 229 10      # Energy of fusion (W/m2)
Qv:           0  W/m2    S2V  1 0 0 1 198 10      # Energy of sublimation (W/m2)
Qa:           0  W/m2    DN   1 0 0 1 136 10      # Advective energy (W/m2)
Qtau:         0  N/m2    DN   1 0 0 1 172 10      # Momentum flux (N/m2)
DelSurfHeat:  0  J/m2    INC  1 0 0 1 137 10      # Change in surface heat storage (J/m2)
DelColdCont:  0  J/m2    INC  1 0 0 1 138 10      # Change in snow cold content (J/m2)
BR:           0  -       -    1 0 1 1 256 10      # Bowen ratio
EF:           0  -       -    1 0 1 1 256 10      # Evaporative fraction
Rnet:         0  W/m2    DN   1 0 1 1 256 10      # Total net radiation

#Water balance components
Snowf:        1  kg/m2s  DN   1 0 0 1 161 10000   # Snowfall rate (kg/m2s)
Rainf:        1  kg/m2s  DN   1 0 0 1 162 10000   # Rainfall rate (kg/m2s)
RainfConv:    1  kg/m2s  DN   1 0 0 1  63 10000   # Convective rainfall rate (kg/m2s)
TotalPrecip:  1  kg/m2s  DN   1 0 0 1  61 10000   # Total precipitation rate (kg/m2s)
Evap:         1  kg/m2s  UP   1 0 0 1  57 10000   # Total evapotranspiration (kg/m2s)
Qs:           1  kg/m2s  OUT  1 0 0 1 235 10000   # Surface runoff (kg/m2s)
Qrec:         0  kg/m2s  IN   1 0 0 1 163 10000   # Recharge (kg/m2s)
Qsb:          1  kg/m2s  OUT  1 0 0 1 234 10000   # Subsurface runoff (kg/m2s)
Qtot:         1  kg/m2s  OUT  1 0 0 1 235 10000   # Total runoff or discharge to stream (kg/m2s)
Qsm:          0  kg/m2s  S2L  1 0 0 1  99 10000   # Snowmelt (kg/m2s)
Qfz:          0  kg/m2s  L2S  1 0 0 1 130 10000   # Refreezing of water in the snowpack (kg/m2s)
Qst:          0  kg/m2s  -    1 0 0 1 131 10000   # Snow throughfall (kg/m2s)
DelSoilMoist: 0  kg/m2   INC  1 0 0 1 132 10000   # Change in soil moisture (kg/m2)
DelSWE:       0  kg/m2   INC  1 0 0 1 133 1000    # Change in snow water equivalent (kg/m2)
DelSurfStor:  0  kg/m2   INC  1 0 0 1 134 1000    # Change in surface water storage (kg/m2)
DelIntercept: 0  kg/m2   INC  1 0 0 1 135 1000    # Change in interception storage (kg/m2)
RHMin:        0  -       -    1 0 0 1  52 10      # Minimum 2-meter relative humidity (-)
Ch:           0  m/s     -    1 0 0 1 208 10      # Surface exchange coefficient for heat
Cm:           0  m/s     -    1 0 0 1 252 10      # Surface exchange coefficient for momentum

#Surface state variables
SnowT:        0  K       -    1 0 0 1 165 10      # Snow surface temperature (K)
VegT:         0  K       -    1 0 0 1 146 10      # Vegetation canopy temperature (K)
BareSoilT:    0  K       -    1 0 0 1 147 10      # Temperature of bare soil (K)
AvgSurfT:     1  K       -    1 0 0 1 148 10      # Average surface temperature (K)
RadT:         0  K       -    1 0 0 1 149 10      # Surface radiative temperature (K)
Albedo:       1  -       -    0 0 0 1  84 100     # Surface albedo (-)
SWE:          1  kg/m2   -    0 0 0 1  65 1000    # Snow Water Equivalent (kg/m2)
SWEVeg:       0  kg/m2   -    1 0 0 1 139 1000    # SWE intercepted by vegetation (kg/m2)
SurfStor:     0  kg/m2   -    1 0 0 1 150 1000    # Surface water storage (kg/m2)

#Subsurface state variables
SoilMoist:    1  kg/m2   -    0 0 0 4  86 1000    # Average layer soil moisture (kg/m2)
SoilTemp:     1  K       -    0 0 0 4  85 1000    # Average layer soil temperature (K)
SmLiqFrac:    0  -       -    0 0 0 4 160 100     # Average layer fraction of liquid moisture (-)
SmFrozFrac:   0  -       -    0 0 0 4 140 100     # Average layer fraction of frozen moisture (-)
SoilWet:      0  -       -    0 0 0 1 144 100     # Total soil wetness (-)
RelSMC:       0  m3/m3   -    0 0 0 4 141 1000    # Relative soil moisture
RootTemp:     0  K       -    0 0 0 1 142 1000    # Rootzone temperature (K)

#Evaporation components
PotEvap:      0  kg/m2s  UP   1 0 0 1 145 1       # Potential evapotranspiration (kg/m2s)
ECanop:       0  kg/m2s  UP   1 0 0 1 200 1       # Interception evaporation (kg/m2s)
TVeg:         0  kg/m2s  UP   1 0 0 1 210 1       # Vegetation transpiration (kg/m2s)
ESoil:        0  kg/m2s  UP   1 0 0 1 199 1       # Bare soil evaporation (kg/m2s)
EWater:       0  kg/m2s  UP   1 0 0 1 197 1       # Open water evaporation (kg/m2s)
RootMoist:    0  kg/m2   -    0 0 0 1 171 1       # Root zone soil moisture (kg/m2)
CanopInt:     0  kg/m2   -    0 0 0 1 223 1000    # Total canopy water storage (kg/m2)
EvapSnow:     0  kg/m2s  -    1 0 0 1 173 1000    # Snow evaporation (kg/m2s)
SubSnow:      0  kg/m2s  -    1 0 0 1 198 1000    # Snow sublimation (kg/m2s)
SubSurf:      0  kg/m2s  -    1 0 0 1 143 1000    # Sublimation of the snow free area (kg/m2s)
ACond:        0  m/s     -    1 0 0 1 179 100000  # Aerodynamic conductance
CCond:        0  m/s     -    1 0 0 1 181 100000  # Canopy conductance
SoilET:       0  kg/m2   -    1 0 0 1 256 1       # Soil evaporation
AResist:      0  s/m     -    1 0 0 1 256 1       # Aerodynamic resistance

#Other hydrologic variables
WaterTableD:  0  m       -    0 0 0 1 174 1       # Water table depth (m)
TWS:          0  mm      -    0 0 0 1 175 1       # Terrestrial water storage (mm)
GWS:          0  mm      -    0 0 0 1 176 1       # Ground water storage (mm)

#Cold season processes
Snowcover:    0  -       -    0 0 0 1 238 100     # Snow cover (-)
SAlbedo:      0  -       -    0 0 0 1 184 1000    # Albedo of the snow-covered area (-)
SnowTProf:    0  K       -    0 0 0 1 239 1000    # Temperature of the snow pack (K)
SnowDepth:    0  m       -    0 0 0 1  66 1000    # Snow depth (m)
SLiqFrac:     0  -       -    0 0 0 1 185 1000    # Fraction of SWE in the liquid phase
SnowThresh:   0  -       -    0 0 0 1  66 1000    # Snow depth threshold (m)

#Variables to compared against remote sensed data
LWup:         0  W/m2    UP   1 0 0 1 212 1       # Longwave radiation up from the surface (W/m2)

#Carbon variables
GPP:          0  kg/m2s2 DN   1 0 0 1 256 1       # Gross Primary Production
NPP:          0  kg/m2s2 DN   1 0 0 1 256 1       # Net Primary Production
NEE:          0  kg/m2s2 UP   1 0 0 1 256 1       # Net Ecosystem Exchange
AutoResp:     0  kg/m2s2 UP   1 0 0 1 256 1       # Autotrophic respiration
HeteroResp:   0  kg/m2s2 UP   1 0 0 1 256 1       # Heterotrophic respiration
LeafResp:     0  kg/m2s2 UP   1 0 0 1 256 1       # Leaf respiration
TotSoilCarb:  0  kg/m2   -    1 0 0 1 256 1       # Total soil carbon
TotLivBiom:   0  kg/m2   -    1 0 0 1 256 1       # Total living biomass

#Forcings
Wind_f:       1  m/s     -    1 0 0 1  32 10      # Near surface wind (m/s)
Rainf_f:      1  kg/m2s  DN   1 0 0 1 162 1000    # Average rainfall rate
Snowf_f:      0  kg/m2s  DN   1 0 0 1 161 1000    # Average snowfall rate
CRainf_f:     1  kg/m2   DN   1 0 0 1  63 1000    # Average convective rainfall rate
Tair_f:       1  K       -    1 0 0 1  11 10      # Near surface air temperature
Qair_f:       1  kg/kg   -    1 0 0 1  51 1000    # Near surface specific humidity
Psurf_f:      1  Pa      -    1 0 0 1   1 10      # Surface pressure
SWdown_f:     1  W/m2    DN   1 0 0 1 204 10      # Surface incident shortwave radiation
LWdown_f:     1  W/m2    DN   1 0 0 1 205 10      # Surface incident longwave radiation
PARDR_f:      0  W/m2    DN   1 0 0 1 256 10      # Surface incident PAR direct
PARDF_f:      0  W/m2    DN   1 0 0 1 256 10      # Surface incident PAR diffuse

#Additional forcings
DirectSW_f:   0  W/m2    -    1 0 0 1 166 10      # Surface direct incident shortwave radiation
DiffuseSW_f:  0  W/m2    -    1 0 0 1 167 10      # Surface diffuse incident shortwave radiation
NWind_f:      0  m/s     N    1 0 0 1  34 10      # Northward wind
EWind_f:      0  m/s     E    1 0 0 1  33 10      # Eastward wind
FHeight_f:    0  m       -    1 0 0 1 256 10      # Height of forcing variables
Ch_f:         0  m/s     -    1 0 0 1 208 10      # Surface exchange coefficient for heat
Cm_f:         0  m/s     -    1 0 0 1 252 10      # Surface exchange coefficient for momentum
Emiss_f:      0  -       -    1 0 0 1 256 10      # Surface emissivity
MixRatio_f:   0  kg/kg   -    1 0 0 1  53 10      # Surface mixing ratio
CosZenith_f:  0  -       -    1 0 0 1 256 10      # Cosine of zenith angle
Albedo_f:     0  -       -    1 0 0 1  84 10      # Surface albedo
CAPE_f:       0  J/kg    -    1 0 0 1 157 10      # Convective Available Potential Energy
Z0brd:        0  m       -    1 0 0 1 256 1       # Z0brd
T2diag:       0  K       -    1 0 0 1 256 1       # Diagnostic t2
Q2diag:       0  kg/kg   -    1 0 0 1 256 1       # Diagnostic q2
Snowflag_f:   0  -       -    1 0 0 1 256 1       # Snowflag
Density_f:    0  kg/m3   -    1 0 0 1 256 1       # Atmospheric density
VaporPress_f: 0  -       -    1 0 0 1 256 1       # Vapor pressure
VaporPressDeficit_f: 0  -  -  1 0 0 1 256 1       # Vapor pressure deficit

#Additional FEWSNET Forcings
PET_f:         0 kg/m2s  -    0 0 0 1 228 1000    # Average PET rate 
RefET_f:       0 kg/m2s  -    0 0 0 1 256 1000    # Average RefET rate 
TotalPrecip_f: 0 kg/m2   DN   0 0 0 1 256 1000    # Total precipitation

#Parameters
Landmask:     0  -       -    0 0 0 1  81 1       # Land mask (0 - Water, 1 - Land)
Landcover:    0  -       -    0 0 0 1 225 1       # Land cover
Soiltype:     0  -       -    0 0 0 1 224 1       # Soil type
SandFrac:     0  -       -    0 0 0 1 256 1       # Sand fraction
ClayFrac:     0  -       -    0 0 0 1 256 1       # Clay fraction
SiltFrac:     0  -       -    0 0 0 1 256 1       # Silt fraction
Porosity:     0  -       -    0 0 0 1 240 1       # Porosity
Soilcolor:    0  -       -    0 0 0 1 256 1       # Soil color
Elevation:    0  m       -    0 0 0 1 196 10      # Elevation
Slope:        0  -       -    0 0 0 1 222 10      # Slope
LAI:          0  -       -    0 0 0 1 182 100     # LAI
SAI:          0  -       -    0 0 0 1 256 100     # SAI
Snfralbedo:   0  -       -    0 0 0 1 184 100     # Snow fraction albedo
Mxsnalbedo:   0  -       -    0 0 0 1 159 100     # Maximum snow albedo
Greenness:    0  -       -    0 0 0 1  87 100     # Greenness
Roughness:    0  m       -    0 0 0 1  83 10      # Roughness
Tempbot:      0  K       -    0 0 0 1 256 10      # Bottom soil temperature

#Routing
Streamflow:   0  m3/s    -    1 0 0 1 256 10      # Streamflow

#VIC PET output
vic_pet_satsoil:  0  kg/m2s  -    1 0 0 1 166 1   # Potential evap from saturated bare soil
vic_pet_h2osurf:  0  kg/m2s  -    1 0 0 1 166 1   # Potential evap from open water
vic_pet_short:    0  kg/m2s  -    1 0 0 1 166 1   # Potential evap (transpiration only) from short reference crop (grass)
vic_pet_tall:     0  kg/m2s  -    1 0 0 1 166 1   # Potential evap (transpiration only) from tall reference crop (alfalfa)
vic_pet_natveg:   0  kg/m2s  -    1 0 0 1 166 1   # Potential evap (transpiration only) from current vegetation and current canopy resistance
vic_pet_vegnocr:  0  kg/m2s  -    1 0 0 1 166 1   # Potential evap (transpiration only) from current vegetation and 0 canopy resistance

#FLDAS-WRSI components
SOS:                      0      - - 0 0 0 1 0 10 # Start-of-season [in dekads]
WRSI:                     0      - - 0 0 0 1 0 10 # Water requirement satisfaction index [ratio]
KF2:                      0      % - 0 0 0 1 0 10 # Percent of Season [%]
SumWR:                    0  kg/m2 - 0 0 0 1 0 10 # Sum of Water Requirement [mm]
SumET:                    0  kg/m2 - 0 0 0 1 0 10 # Sum of Evapotranspiration [mm]
SWI:                      0      % - 0 0 0 1 0 10 # Soil Water Index [%]
SOSa:                     0      - - 0 0 0 1 0 10 # Start-of-season Anomaly [in dekads]
TotalSurplusWater:        0  kg/m2 - 0 0 0 1 0 10 # Total surplus water [mm]
MaxSurplusWater:          0  kg/m2 - 0 0 0 1 0 10 # Max surplus water experienced in 1 dekad [mm]
TotalWaterDeficit:        0  kg/m2 - 0 0 0 1 0 10 # Total water deficit [mm]
MaxWaterDeficit:          0  kg/m2 - 0 0 0 1 0 10 # Max water deficit experienced in 1 dekad [mm]
TotalAETInitial:          0  kg/m2 - 0 0 0 1 0 10 # Actual evapotranspiration ~ Initial stage [mm]
TotalWRInitial:           0  kg/m2 - 0 0 0 1 0 10 # Water requirement ~ Initial stage [mm]
TotalSurplusWaterInitial: 0  kg/m2 - 0 0 0 1 0 10 # Surplus water ~ Initial stage [mm]
TotalWaterDeficitInitial: 0  kg/m2 - 0 0 0 1 0 10 # Water deficit ~ Initial stage [mm]
TotalAETVeg:              0  kg/m2 - 0 0 0 1 0 10 # Actual evapotranspiration ~ Vegetative stage [mm]
TotalWRVeg:               0  kg/m2 - 0 0 0 1 0 10 # Water requirement ~ Vegetative stage [mm]
TotalSurplusWaterVeg:     0  kg/m2 - 0 0 0 1 0 10 # Surplus water ~ Vegetative stage [mm]
TotalWaterDeficitVeg:     0  kg/m2 - 0 0 0 1 0 10 # Water deficit ~ Vegetative stage [mm]
TotalAETFlower:           0  kg/m2 - 0 0 0 1 0 10 # Actual evapotranspiration ~ Flowering stage [mm]
TotalWRFlower:            0  kg/m2 - 0 0 0 1 0 10 # Water requirement ~ Flowering stage [mm]
TotalSurplusWaterFlower:  0  kg/m2 - 0 0 0 1 0 10 # Surplus water ~ Flowering stage [mm]
TotalWaterDeficitFlower:  0  kg/m2 - 0 0 0 1 0 10 # Water deficit ~ Flowering stage [mm]
TotalAETRipe:             0  kg/m2 - 0 0 0 1 0 10 # Actual evapotranspiration ~ Ripening stage [mm]
TotalWRRipe:              0  kg/m2 - 0 0 0 1 0 10 # Water requirement ~ Ripening stage [mm]
TotalSurplusWaterRipe:    0  kg/m2 - 0 0 0 1 0 10 # Surplus water ~ Ripening stage [mm]
TotalWaterDeficitRipe:    0  kg/m2 - 0 0 0 1 0 10 # Water deficit ~ Ripening stage [mm]
PermWiltDate:             0      - - 0 0 0 1 0 10 # Permanent wilting date [dekad]
Wilting1:                 0      - - 0 0 0 1 0 10 # First wilting date [dekad]
Wilting2:                 0      - - 0 0 0 1 0 10 # Second wilting date [dekad]
WRSIa:                    0      - - 0 0 0 1 0 10 # WRSI anomaly [-]
growing_season:           0      - - 0 0 0 1 0 10 # Growing season [season-year]
WHC:                      0  kg/m2 - 0 0 0 1 0 10 # Water holding capacity; parameter [mm]
LGP:                      0      - - 0 0 0 1 0 10 # Length of growing period; parameter [dekad]
WR_TimeStep:              0  kg/m2 - 0 0 0 1 0 10 # Water requirement per timestep(dekad) [mm]
AET_TimeStep:             0  kg/m2 - 0 0 0 1 0 10 # Actual ET per timestep [mm]
WRSI_TimeStep:            0      - - 0 0 0 1 0 10 # WRSI per timestep [-]
SurplusWater_TimeStep:    0  kg/m2 - 0 0 0 1 0 10 # Surplus water per timestep [mm]

#SacHTET specific output
sac_tsint:       0  K        -   0 0 0 1 256 10  # Soil temperature of inteneded layer
sac_swint:       0  m3/m3    -   0 0 0 1 256 10  # Total volumetric soil moisture content of intended layer
sac_swhint:      0  m3/m3    -   0 0 0 1 256 10  # Liquid volumetric soil moisture content of intended layer
sac_frost:       0  -        -   0 0 0 1 256 10  # Frost
sac_uztwc:       0  mm       -   0 0 0 1 256 10  # UZTWC
sac_uzfwc:       0  mm       -   0 0 0 1 256 10  # UZFWC
sac_lztwc:       0  mm       -   0 0 0 1 256 10  # LZTWC
sac_lzfsc:       0  mm       -   0 0 0 1 256 10  # LZFSC
sac_lzfpc:       0  mm       -   0 0 0 1 256 10  # LZFPC
sac_adimpc:      0  mm       -   0 0 0 1 256 10  # ADIMPC
sac_uztwh:       0  mm       -   0 0 0 1 256 10  # UZTWH
sac_uzfwh:       0  mm       -   0 0 0 1 256 10  # UZFWH
sac_lztwh:       0  mm       -   0 0 0 1 256 10  # LZTWH
sac_lzfsh:       0  mm       -   0 0 0 1 256 10  # LZFSH
sac_lzfph:       0  mm       -   0 0 0 1 256 10  # LZFPH

#Snow17 specific output
snow17_swe:      0  kg/m2    -   0 0 0 1 256 10  # SWE
snow17_aeadj:    0  mm       -   0 0 0 1 256 10  # AEADJ
snow17_neghs:    0  mm       -   0 0 0 1 256 10  # NEGHS
snow17_liqw:     0  kg/m2    -   0 0 0 1 256 10  # LIQW
snow17_accmax:   0  mm       -   0 0 0 1 256 10  # ACCMAX
snow17_rmlt:     0  kg/m2    -   0 0 0 1 256 10  # RMLT

#Lake output
Lake_Tsnow:      0  K        -   0 0 0 1 256 10  # Lake temperature at the air snow interface
Lake_Tice:       0  K        -   0 0 0 1 256 10  # Lake temperature at the snow snow interface
Lake_Tmnw:       0  K        -   0 0 0 1 256 10  # Mean temperature of the water column
Lake_Twml:       0  K        -   0 0 0 1 256 10  # Lake temperature of the mixed layer
Lake_Tbot:       0  K        -   0 0 0 1 256 10  # Lake temperature at the water bottom
Lake_Tb1:        0  K        -   0 0 0 1 256 10  # Temperature at the bottom of upper layer of sediments
Lake_CT:         0  -        -   0 0 0 1 256 10  # Thermocline shape factor of lake
Lake_Hice:       0  -        -   0 0 0 1 256 10  # Ice thickness above lake
Lake_Hml:        0  -        -   0 0 0 1 256 10  # Thickness of mixed layer of lake
Lake_Hb1:        0  -        -   0 0 0 1 256 10  # Thickness of upper layer of bottom sediments
Lake_Walbedo:    0  -        -   0 0 0 1 256 10  # Water surface albedo over lake
Lake_IceAlbedo:  0  -        -   0 0 0 1 256 10  # Ice surface albedo over lake
Lake_SnowAlbedo: 0 -         -   0 0 0 1 256 10  # Snow surface albedo over lake
Lake_UFRa:       0  -        -   0 0 0 1 256 10  # Lake friction velocity in air
Lake_UFRw:       0  -        -   0 0 0 1 256 10  # Lake friction velocity in surface water
Lake_WConv:      0  -        -   0 0 0 1 256 10  # Lake convective velocity scale
Lake_IW:         0  -        -   0 0 0 1 256 10  # Lake radiation flux at the interface
Lake_Qbot:       0  -        -   0 0 0 1 256 10  # Lake heat flux across water sediment boundary

#HyMAP routing output
RiverStor:       0  m3       -   0 0 0 1 256 10  # River water storage
RiverDepth:      0  m        -   0 0 0 1 256 10  # River depth
RiverVelocity:   0  m/s      -   0 0 0 1 256 10  # River flow velocity
FloodQ:          0  m3/s     -   0 0 0 1 256 10  # Floodplain water discharge
FloodEvap:       0  kg/m2s   -   0 0 0 1 256 10  # Floodplain evaporation
FloodStor:       0  m3       -   0 0 0 1 256 10  # Floodplain water storage
FloodDepth:      0  m        -   0 0 0 1 256 10  # Floodplain depth
FloodVelocity:   0  m/s      -   0 0 0 1 256 10  # Floodplain flow velocity
FloodedFrac:     0  -        -   0 0 0 1 256 10  # Flooded fraction
FloodedArea:     0  m2       -   0 0 0 1 256 10  # Flooded area
SurfElev:        0  m        -   0 0 0 1 256 10  # Surface water elevation
RunoffStor:      0  mm       -   0 0 0 1 256 10  # Runoff reservoir storage
BaseflowStor:    0  mm       -   0 0 0 1 256 10  # Baseflow reservoir storage
RunoffDWI:       0  mm       -   0 0 0 1 256 10  # Runoff deep water infiltration
BaseflowDWI:     0  mm       -   0 0 0 1 256 10  # Baseflow deep water infiltration
SWS:             0  mm       -   0 0 0 1 256 10  # Surface water storage
EvapWater:       0  kg/m2s   -   0 0 0 1 256 10  # Potential evaporation from open water
EvapDif:         0  kg/m2s   -   0 0 0 1 256 10  # Differential evaporation (potential evaporation - actual evapotranspiration)

#RTM output
RTM emissivity:  0  -        -   0 0 0 1 256 10  # RTM emissivity
RTM Tb:          0  K        -   0 0 0 1 256 10  # RTM brightness temperature
RTM SoilMoist:   0  m3/m3    -   0 0 0 1 256 10  # RTM soil moisture

#Irrigation output
Irrigated water: 0  kg/m2s   -   0 0 0 1 256 10  # Irrigated water amount

#AWRAL600 output
e0:           1  mm      -    0 0 0 1 0 1 # potential evaporation
etot:         1  mm      -    0 0 0 1 0 1 # actual evapotranspiration
Qtot:         1  mm      -    0 0 0 1 0 1 # total discharge to stream
sr:           1  mm      -    0 0 0 1 0 1 # volume of water in the surface water store
sg:           1  mm      -    0 0 0 1 0 1 # groundwater storage in the unconfined aquifer
dd:           1  mm      -    0 0 0 1 0 1 # vertical drainage from the bottom of the deep soil layer
s0:           1  mm      -    0 0 0 2 0 1 # water storage in the surface soil layer for each hru
ss:           1  mm      -    0 0 0 2 0 1 # water content of the shallow soil store for each hru
sd:           1  mm      -    0 0 0 2 0 1 # water content of the deep soil store for each hru
mleaf:        1  kg/m2   -    0 0 0 2 0 1 # leaf biomass for each hru
s0_avg:       1  mm      -    0 0 0 1 0 1 # water storage in the surface soil layer
ss_avg:       1  mm      -    0 0 0 1 0 1 # water content of the shallow soil store
sd_avg:       1  mm      -    0 0 0 1 0 1 # water content of the deep soil store

# SnowModel-specific fields:
SM_SWE:          1  m       -    0 0 0 1  65 1000    # Snow Water Equivalent (kg/m2)
SM_SnowDepth:    1  m       -    0 0 0 1  66 1000    # Snow depth (m)
SM_SnowDensity:  1  kg/m3   -    0 0 0 1 900 10      # Snow density (kg/m3) 
SM_Snowcover:    0  -       -    0 0 0 1 238 100     # Snow cover (-)
SM_SLiqFrac:     0  -       -    0 0 0 1 185 1000    # Fraction of SWE in the liquid phase
SM_SWEVeg:       0  kg/m2   -    1 0 0 1 139 1000    # SWE intercepted by vegetation (kg/m2)
SM_Albedo:       1  -       -    1 0 0 1  84 100     # Surface albedo (-)
SM_SAlbedo:      0  -       -    0 0 0 1 184 1000    # Albedo of the snow-covered area (-)
# Other fields -- summed output:
SM_Qs:           0  m       OUT  3 0 0 1 235 10000   # Surface runoff from snowpack / top-soil (m/timestep)
SM_Qsm:          0  m       S2L  3 0 0 1  99 10000   # Snowmelt (kg/m2s)
SM_SubSnow:      0  m       -    3 0 0 1 198 1000    # Snow sublimation (m)
SM_Snowf:        1  m       DN   3 0 0 1 161 10000   # Snowfall rate (m/timestep)
SM_Rainf:        1  m       DN   3 0 0 1 162 10000   # Rainfall rate (m/timestep)
SM_TotalPrecip:  1  m       DN   3 0 0 1  61 10000   # Total precipitation rate (m/timestep)
# SnowModel-modified forcings:
SM_SWdown:    1  W/m2    DN   1 0 0 1 204 10         # SnowModel-modified SWdown
SM_LWdown:    1  W/m2    DN   1 0 0 1 205 10         # SnowModel-modified LWdown
SM_NWind:     1  m/s     N    1 0 0 1  34 10         # SnowModel-modified NWind
SM_EWind:     1  m/s     E    1 0 0 1  33 10         # SnowModel-modified EWind
....

