= How to create LIS 7 testcases
:author: James Geiger
:revnumber: 4
:revdate: 20 Dec 2018
//:sectnums:

== Introduction

This document describes how to create a functional or acceptance testcase for LIS 7.

I will use the testcase for the NAM 242 forcing reader as an example. The goal of this document is to guide the reader into creating the following files:

. README
+
The README file provides a description of the testcase including a high-level description of the configuration and instructions on how to run the testcase.

. ldt.config
+
The ldt.config file is the configuration file used to run LDT to produce the input domain and parameter file for LIS (e.g.: lis_input.d01.nc).

. input.ctl
+
The input.ctl file is a GrADS descriptor file used to display the input paramter file (e.g.: lis_input.d01.nc).

. lis.config
+
The lis.config file is the configuration file used to run LIS.

. MODEL_OUTPUT_LIST.TBL
+
The MODEL_OUTPUT_LIST.TBL file used by the lis.config file is also used to run LIS.

. output.ctl
+
The output.ctl file is a GrADS descriptor file used to display the output from the LIS run.

. testcase.ctl
+
The testcase.ctl file is a GrADS descriptor file used to display the packaged output from the OUTPUT tar file (e.g.: nam242forcingtest_output_v72.tar.gz).

. nam242forcingtest_ldt_v72.tar.gz
+
This is the LDT tar file. It contains all the data needed to run LDT to produce the input domain and parameter file for LIS (e.g.: lis_input.d01.nc).

. nam242forcingtest_input_v72.tar.gz
+
This is the INPUT tar file. It contains all the data needed to run LIS.

. nam242forcingtest_output_v72.tar.gz
+
This is the OUTPUT tar file. It contains all the output from the LIS run.

Files 1. though 7. are kept with the LIS source code. See testcases/metforcing/nam242. Files 8., 9., and 10. are stored on our data portal server.

Creating a testcase is done in four steps.

Step 1) focuses on the README file.

Step 2) focuses on the ldt.config file, input.ctl file, and the LDT tar file (e.g.: nam242forcingtest_ldt_v72.tar.gz).

Step 3) focuses on the INPUT tar file (e.g.: nam242forcingtest_input_v72.tar.gz).

Step 4) focuses on the lis.config file, MODEL_OUTPUT_LIST.TBL file, output.ctl file, testcase.ctl file, and the OUTPUT tar file (e.g.: nam242forcingtest_output_v72.tar.gz).

[NOTE]
====
These tests are run on systems other than discover, so the files that you create must be self-contained.  For example, the config files should *not* refer to /discover/nobackup/... .  Please use files and results generated in previous steps (see, for example, Step 4.3), to verify that your testcase is both complete and self-contained.
====

[IMPORTANT]
====
This should go without saying: please do *not* commit the ldt, input, and output tar.gz files into the repository.  Those files will be transferred to our data portal.
====


== Step 1
. Write the README file. Please see the README file in testcases/metforcing/nam242 for an example. This file should be saved in the LIS source code in the appropriate testcases sub-directory.

== Step 2
. Create a clean working directory.

. Create the ldt.config file as appropriate for your testcase. A copy should be saved in the LIS source code in the appropriate testcases sub-directory.
+
Create an input directory and place all necessary input files into it.
+
....
% ls input
input/LS_PARAMETERS/UMD/25KM/landcover_UMD.1gd4r
input/LS_PARAMETERS/UMD/25KM/landmask_UMD.1gd4r
input/LS_PARAMETERS/UMD/25KM/elev_GTOPO30.1gd4r
input/LS_PARAMETERS/metforcing_parms/NAM/terrain.242.grb
....

. Run LDT to produce the input domain and parameter file for LIS (e.g.: lis_input.d01.nc).

. Create an input.ctl GrADS descriptor file for viewing the input paramter file. A copy should be saved in the LIS source code in the appropriate testcases sub-directory.

. Rename the log file from the LDT run to ldtlog_testcase.0000. Copy the input domain and parameter file to lis_input_testcase.d01.nc.

. Create the LDT tar file.
+
....
% tar cf nam242forcingtest_ldt_v72.tar ldtlog_testcase.0000 \
                                       lis_input_testcase.d01.nc \
                                       input
% gzip nam242forcingtest_ldt_v72.tar
....
+
This provides the user with all the files and data needed to rerun the LDT preprocessing step.

== Step 3
. Create a clean working directory.

. Copy the input domain and parameter file (e.g.: lis_input.d01.nc) from Step 2.

. Create an input directory and place all necessary input files (and only necessary files) into it, including any parameter files that are *not* processed by LDT. Note that you must create an input/forcing_variables.txt file that specifies which forcing variables are needed by LIS for this testcase.
+
....
% ls input
input/forcing_variables.txt
input/MET_FORCING/NAM242/20120901/00/fh.0000_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120901/00/fh.0003_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120901/00/fh.0006_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120901/00/fh.0009_tl.press_gr.awp242
                             .
                             .
                             .
input/MET_FORCING/NAM242/20120903/18/fh.0003_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120903/18/fh.0006_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120903/18/fh.0009_tl.press_gr.awp242
input/MET_FORCING/NAM242/20120903/18/fh.0012_tl.press_gr.awp242
....

. Create the INPUT tar file.
+
....
% tar cf nam242forcingtest_input_v72.tar lis_input.d01.nc \
                                         input
% gzip nam242forcingtest_input_v72.tar
....
+
This provides the user with all the files and data needed to run LIS.

== Step 4

. Create a clean working directory.

. Create the lis.config file and MODEL_OUTPUT_LIST.TBL file as appropriate for your testcase. Copies should be saved in the LIS source code in the appropriate testcases sub-directory.

. Copy and unpack the nam242forcingtest_input_v72.tar.gz file from Step 3.
+
....
% gzip -dc nam242forcingtest_input_v72.tar.gz | tar xf -
....

. Run LIS to produce the output data.

. Create an output.ctl GrADS descriptor file for viewing the output data. A copy should be saved in the LIS source code in the appropriate testcases sub-directory.

. Rename the OUTPUT directory to TARGET_OUTPUT.

. Move the lislog.00* files into the TARGET_OUTPUT directory.
+
....
% ls TARGET_OUTPUT
lislog.0000  SURFACEMODEL  SURFACEMODEL.d01.stats
....

. Create a testcase.ctl GrADS descriptor file for viewing the output data in the TARGET_OUTPUT directory. A copy should be saved in the LIS source code in the appropriate testcases sub-directory.

. Create the OUTPUT tar file.
+
....
% tar cf nam242forcingtest_output_v72.tar TARGET_OUTPUT
% gzip nam242forcingtest_output_v72.tar
....
+
This provides the user with all the files and data needed to compare the LIS testcase.

